### ISSUE TITLE
Sort search results by popularity

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#102]

**Comment by aldenstpage** [comment]
Easy change once #50 is implemented

**Comment by aldenstpage** [comment]
@brenoferreira Is this a feature that would be of interest to you? I'm interested in finding alternative ways to rank search results, but I have a feeling that ranking by view count is not going to be particularly useful for finding the best content in the catalog.

**Comment by brenoferreira** [comment]
View count will probably favour images that are already first in the results. Maybe once we implement features such as image download, and a way of tracking re-usage of the images, we could use those metrics along with view count to create a better indicator of popularity. What do you think?

**Comment by janeatcc** [comment]
Fyi that image download would still be a way to download the image directly from the provider (as currently right clicking does) as we don't host on our servers. If we were to change this up, we'd have to discuss with the product team, including counsel. 

Agree with the general approach that whatever we do WRT tracking re-use in the future should be factored in here though.

**Comment by kgodey** [comment]
We don't have a good way to measure popularity, closing.
