### ISSUE TITLE
Use `removed_from_source` field to filter dead links from Elasticsearch

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#112]
We routinely crawl the web and consume APIs to find CC licensed works. As a search engine, we have to deal with link rot; images are often deleted or moved from their original location. During crawling, if we detect that an image has been deleted, we will mark it with the `removed_from_source` field in our database. 

`ingestion-server`, our tool for building an Elasticsearch index, will need to be updated to discard images where `removed_from_source=True`.

**Comment by aldenstpage** [comment]
Marked as low priority; dead links are filtered from search results in realtime now.

**Comment by alirizwi** [comment]
@aldenstpage I want to work on this issue. Can you guide me how to proceed with this?

**Comment by VIGS25** [comment]
@alirizwi: I am actually working on this right now.
