### ISSUE TITLE
Remove all fields not used as search criteria from Elasticsearch

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#148]
Our Elasticsearch cluster contains many fields that are not used directly in search, including:
```
    identifier = Keyword()
    creator_url = Keyword()
    created_on = Date()
    url = Keyword()
    source = Keyword()
    meta_data = Nested()
```

Cutting these fields from Elasticsearch may significantly lower the size of our data in memory, which would allow us to run a leaner and cheaper Elasticsearch cluster, or at the very least improve search performance.

**Comment by VIGS25** [comment]
The feature in itself is not hard to implement, but how would a test be written for this part, since the `sample_data.csv` is quite small, and the performance gains won't be noticeable
