### ISSUE TITLE
Cache top N searches (N=1,000,000?) in Redis

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#152]

**Comment by aldenstpage** [comment]
Assigned "low priority" because performance is adequate at current levels of traffic

**Comment by muarachmann** [comment]
Hi @aldenstpage I would love to take on this.

**Comment by aldenstpage** [comment]
Hi @muarachmann, I suggest taking a look at a different issue. We don't have an immediate need for this performance improvement, and there are some nuances to this that may make it difficult for an external contributor to address.

**Comment by muarachmann** [comment]
Hi @aldenstpage thanks for your reply, can you reference me to which issue i could easily pickup then :)
