### ISSUE TITLE
Gauge quality of search results in automated tests

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#188]
We need a way to empirically evaluate the quality of our search results as we make changes to our [Elasticsearch queries](https://github.com/creativecommons/cccatalog-api/blob/master/cccatalog-api/cccatalog/api/controllers/search_controller.py).

This entails compiling some sample search data and ensuring that the right documents float to the top.

**Comment by kgodey** [comment]
Duplicate of #219.
