### ISSUE TITLE
Usable `creator` search parameter

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#192]
Users of the API can filter by creator, but they have to include other keywords, limiting the usefulness of this feature. We should either intelligently reintroduce the `creator` field as a default search parameter, or allow users to make `creator` queries without filling in the `q` parameter.

While it seem reasonable to include the creator as a default search field, in practice I found that this produces lots of low-relevance search results, so a different approach is needed.

**Comment by janeatcc** [comment]
Since this is still in discussion, throwing my two cents in officially that we try searching across the creator field from approved providers only, e.g. creator field for all Met images.

**Comment by aldenstpage** [comment]
Hi Jane, for now, I've implemented a `creator` special search parameter (as well as `tags` and `title`), which Breno can use to implement an advanced search box.

I think you're right that excluding social providers like Flickr and Behance could make this parameter usable; screen names aren't very useful search criteria. I can add this feature to the generic search path but still allow optional use of the new advanced search parameters.
