### ISSUE TITLE
Search results matching full string when search term contains double quotes

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-api#204]
When searching, for example, [for creator "Claude Monet"](https://ccsearch.creativecommons.org/search?q=%22Claude%20Monet%22&searchBy=creator), many of the results are from creators named "Claude <something>".

It would be better if the search term has double quotes, the search is performed matching the full search term string.

In the example above, the results would contain only images with the creator being "Claude Monet", for example https://ccsearch.creativecommons.org/photos/6a93f964-786d-4dbd-8925-df30ef611656

**Comment by janeatcc** [comment]
Yes, intuitively it makes sense for user to expect Claude AND Monet to be contained in search results for creator.

**Comment by kgodey** [comment]
Adding this to the current sprint since it affects the search experience and should be easy to fix.

**Comment by aldenstpage** [comment]
I'm going to add support for [Lucene-style searches](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Wildcard%20Searches) to api-dev tomorrow.
