### ISSUE TITLE
Improve quality, maintainability, and coverage of ingestion server tests

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#217]
Currently, we have a big CSV file that we load sample data from. This works well as an end-to-end test of ingestion, but it's not so great for testing individual features, since it tightly couples the tests to the sample data. It has the added downside of requiring us to spin up a live version of `ingestion-server`, which is significant because it takes 30+ seconds to start Elasticsearch.

It would be nice to have some unit tests that instead use mocked data and dependencies to quickly verify the functionality without running an end-to-end-test.

**Comment by catherinehoang** [comment]
Hi! I'd like to work on this

**Comment by aldenstpage** [comment]
Hi @catherinehoang, that's great! I added the `in progress` to indicate you've claimed the issue.

**Comment by catherinehoang** [comment]
@aldenstpage Just to clarify, do you want the new tests to test the same functionalities that are currently tested in integration_tests.py? Or are there specific features you would like tested?

**Comment by aldenstpage** [comment]
@catherinehoang Sorry for the long delay, we are really busy! There are some new features that could use some unit tests, namely those defined in PR #244. We filter out some tags by name and fix malformed URLs. Some of these cases are not covered by the sample data.

After reflecting more on this ticket, I think that it will be very difficult to accurately mock features of the ingestion server because we heavily depend on special features offered by PostgreSQL. Perhaps the scope of improving the tests should be reduced to fixing the messy sample data loading and replacing it with something sane (see here: https://github.com/creativecommons/cccatalog-api/blob/master/ingestion_server/test/integration_tests.py#L43 ; it's a total disaster right now!) and implementing some unit tests for new functionality.

**Comment by catherinehoang** [comment]
@aldenstpage No worries! I can definitely work on adding tests to the new features.

**Comment by kgodey** [comment]
Removing "in progress" tag since there has been no update for 7+ days.

**Comment by aldenstpage** [comment]
I'm going to close this issue since the Ingestion Server test coverage has improved (we have unit tests cleanup functions + other pre-indexing munging now), and because there are some issues in other areas that need to take priority.
