### ISSUE TITLE
Fork willnorris/imageproxy so it can handle incorrect content types

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#218]
Some image providers do not correctly handle `content_type` headers or even correct status codes. This makes our lives as developers difficult because we cannot produce thumbnails or determine that the image has been moved/deleted. See #197 and #198 for details; this is especially a problem with the MET dataset.

To fix this, we should customize `willnorris/imageproxy` (ideally in a configurable and upstream-friendly way, so we can share our changes with the community) that will allow the imageproxy to handle incorrect content type headers.

**Comment by VIGS25** [comment]
I'd like to work on this issue. Would the [willnorris-imageproxy](https://github.com/willnorris/imageproxy) be forked into a separate folder under cccatalog-api, and then we make changes to this folder, and change `docker-compose.yml` accordingly?

**Comment by aldenstpage** [comment]
Since the ideal outcome is upstreaming, I'd recommend forking it into your own personal repository at first. I can reach out to Will Norris and see if he has any thoughts on this feature so we can make sure we design this in a way that would be likely to be merged.

**Comment by aldenstpage** [comment]
It turns out that the content type issue is due to us being blackholed by an overly aggressive firewall on the MET servers. There won't be any need to implement this change.
