### ISSUE TITLE
Documentation missing an instruction, causing ES to not startup

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-api#221]
The current documentation omits an instruction `vm.max_map_count` which needs to be atleast set to 262144 by editing the `/etc/sysctl.conf` file. Without this the ElasticSearch Docker container fails to start and consequently so does the Django container.

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='es', port=9200): Max retries exceeded
```

Is this an issue with my computer only? Should we add this line to the setup instructions?

**Comment by dhruvkb** [comment]
@kgodey If it could be confirmed that this issue occurs on other computers, I could solve it. It's a pretty simple issue with a well-defined solution.

**Comment by kgodey** [comment]
Tagging @aldenstpage to verify this. @dhruvkb I know a couple of other students have set this project up locally, I'd recommend checking with them on Slack about this issue.

**Comment by VIGS25** [comment]
I had the same issue as well, and using @dhruvkb's strategy was what I did too.

**Comment by aldenstpage** [comment]
The README has been updated with some additional detail on troubleshooting Elasticsearch
