### ISSUE TITLE
Admin site unreachable because of missing packages

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-api#222]
The Django admin site (at `/admin`) cannot be opened currently. Visiting it yields an error in the `django-rest-framework-social-oauth2` package, which on further investigation narrows down to the absence of the `python-social-auth` package amongst other minor things.

Can this issue be verified so that I may submit a PR to fix this issue? This would allow us to access and utilise the Django administrative interface.

**Comment by kgodey** [comment]
Tagging @aldenstpage to verify whether this is desirable.

**Comment by dhruvkb** [comment]
It's been fixed by @aldenstpage himself in 36d9eb2. He removed the `django-rest-framework-social-oauth2` package itself. I'll just close the issue.
