### ISSUE TITLE
Inconsistent pinning of packages in requirements.txt

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-api#223]
The `requirements.txt` file is in a bit of a disarray and can be benefited from a refresh. To elaborate, many packages listed at the bottom seem to be written by hand and are missing version numbers. A lot of sub-dependecies are also missing from the file. At the very least, the discrepancy between `pip freeze` and the `requirements.txt` file should be removed. 

Furthermore since we intend on using the CCCatalogAPI project as an application, we can make use of much better dependency management tooling such as [Pipenv](https://pipenv.readthedocs.io/) or [Poetry](https://poetry.eustace.io/).

**Comment by dhruvkb** [comment]
I'd like to work on this issue. Can I take this up?

**Comment by kgodey** [comment]
This is done.
