### ISSUE TITLE
Preserve metadata in watermarked images

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#232]
We need to preserve EXIF metadata and (maybe?) add [ccREL](https://www.w3.org/Submission/ccREL/) properties to it.

**Comment by aldenstpage** [comment]
@kgodey @janeatcc Will we only be preserving EXIF metadata, or should we be adding attribution metadata as well?

**Comment by kgodey** [comment]
I think adding ccREL data would be great.

**Comment by janeatcc** [comment]
We are preserving all existing metadata (we can't strip it out) and adding ccREL into the exif extension field.. whatever our standard is. :)

**Comment by janeatcc** [comment]
This is the extension for XMP: https://wiki.creativecommons.org/wiki/XMP

**Comment by aldenstpage** [comment]
This will go out in the next API release
