### ISSUE TITLE
Line break attribution in watermarked images

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-api#234]
The watermark text today, if it's long enough, can exceed the width of the image and end up being cut off in the middle.
There should be a way to wrap the text around the image bounds and do line breaks if necessary.

**Comment by dhruvkb** [comment]
@brenoferreira can you show some examples of this issue in action? I'd like to work on this and would need more context to better understand the issue.

**Comment by dhruvkb** [comment]
@brenoferreira and @aldenstpage, this issue has been resolved in #252 and should be closed.
