### ISSUE TITLE
Adjust attribution font size for different image resolutions

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-api#235]
For images with very high resolution, the attribution text can end up looking too small (eg: [here](https://api-dev.creativecommons.engineering/watermark/26fc5746-4731-4540-9412-d0e363373f03)), so we should adjust the font size depending on the image resolution.

**Comment by dhruvkb** [comment]
I'd like to work on this issue and am figuring out a way to do this in conjugation with #234. 

@brenoferreira what is the ideal ratio you are expecting the attribution to be relative to the image dimensions? I think this would differ for landscape and portrait oriented images.

**Comment by dhruvkb** [comment]
This is the thought I'm working on right now.
![image](https://i.imgur.com/eEmxikR.jpg)

If you could, kindly ignore the question in my previous comment, which I had asked in naïvety without thinking the problem through thoroughly, and help me with this new doubt. What value of w (image width) should I use as a breakpoint below which the attribution does not scale?

**Comment by dhruvkb** [comment]
This issue has been fixed with #252. Please consider closing @aldenstpage and @brenoferreira.
