### ISSUE TITLE
Comply with contribution guidelines on wiki

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#240]
https://wikijs.creativecommons.org/tech/github-repo-guidelines

**Comment by dhruvkb** [comment]
@aldenstpage how can one register on the wiki to read more? Is access to the wiki restricted to certain members of the organisation?

**Comment by kgodey** [comment]
@dhruvkb that is our internal wiki and only open to CC staff. I will move the contribution guideline checklist to the public CC Open Source website when I have time.
