### ISSUE TITLE
Watermark view cannot handle images that do not have EXIF data

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-api#247]
The utility function `watermark(image_url, image_info)` returns `watermarked, exif` where `exif` will be `None` if the image at the URL lacks EXIF data embedded in it.

This breaks down in the next line `exif_bytes = piexif.dump(exif)`

**To Reproduce**
Visit `/watermark/{identifier}` for an image without EXIF.

**Expected behavior**
The watermarked image should be returned without EXIF, like the source image.

The solution is simply to check for `exif` being `None` and not embedding `exif_bytes` in the response. Can I open a PR with this solution?

**Comment by dhruvkb** [comment]
I could open a PR with this but it is bound to conflict with a PR towards the resolution #243. This being a rather minor change, could also be worked on in conjunction with issue #243, if @aldenstpage so wishes. This is also affecting the testing of PR #242.

**Comment by aldenstpage** [comment]
Fixed in #252
