### ISSUE TITLE
Allow for two different markers of CCrel metadata in watermark

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-api#250]
One is the normal one that is downloaded that we're setting up now

Two is with some additional code that indicates that user has opted in to provide more information about how they have reused the work. It can be a tracking code or something of that ilk. Not sure. Let's discuss how to do this!

We'll need this before we ship to production.

**Comment by aldenstpage** [comment]
Jane and I discussed this offline. We're going to hold off on adding consent metadata fields until we've put together a practical strategy for tracking reuse of works out in the wild.

**Comment by annatuma** [comment]
Closing this out, we did not move forward with watermarking images at download.
