### ISSUE TITLE
Treat multi-word searches as phrases by default

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#258]
For example, compare these two queries: 

No quotation marks:
https://ccsearch.creativecommons.org/search?q=home%20office&provider=&li=&lt=&searchBy=

Quotation marks:
https://ccsearch.creativecommons.org/search?q=%22home%20office%22&provider&li&lt&searchBy

The first query returns results with really low relevance. It seems that instead of passing a user's phrase straight to the search query string, we should do some preprocessing beforehand.

**Comment by KhalidRmb** [comment]
Hi @aldenstpage! I'm new to CC and I think I can do this one. So basically, in the preprocessing, we have to treat multi-word queries as a single phrase, unlike what's currently happening. May I work on this?

**Comment by aldenstpage** [comment]
It ended up being a problem with our Elasticsearch query and index structure; there was no need to implement any special treatment for phrases.
