### ISSUE TITLE
Ingestion server needs a QA mode for dev testing

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#279]
Ingestion server is responsible for copying data from the upstream source (a PostgreSQL scraped from assorted APIs and Common Crawl) into the API database, cleaning the data, and then indexing it in Elasticsearch.

Right now, the server copies all 300 million records. This poses a problem for us because our development environment can only support maybe 20 million records (as we are running it on much more economical hardware compared with production). As a result, we are using an old and crusty static data set of 10M images that does not adequately reproduce issues we routinely encounter in production.

Ingestion Server's INGEST_UPSTREAM function (see load_sample_data.sh) should have an optional QA parameter that causes the server to instead load a small subset (up to 1,000,000 each) of the upstream data for each provider.

**Comment by annatuma** [comment]
Prioritizing this for Q1 2020, makes sense to get this testing infrastructure in order before we add additional content types.

**Comment by kss682** [comment]
Hi, Can I work on this issue .
