### ISSUE TITLE
Store work descriptions and use them as a component to find relevant search results

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#284]
- We only search based on title and tags right now, but providers often provide descriptions of images which may help with search result relevancy. We should store and use that data.
- Run A/B tests to determine success.

**Comment by aldenstpage** [comment]
The description, when available, is stored in the `metadata` field in the database. You can find some examples of this in the sample data. Implementing this would entail configuring Elasticsearch to store and analyze this field in `ingestion-server`, as well as updating `cccatalog-api` to query against this field.
