### ISSUE TITLE
Implement PageRank-style algorithm to find best search results

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#285]
Info on PageRank algorithm: https://en.wikipedia.org/wiki/PageRank

We would need to use CommonCrawl data to see how many other pages link to the page to get data on the quality of the work (works that are linked to from more places are probably higher quality). We would then use this data in generating our search results.

This is a massive amount of work which will require several GitHub issues, this issue is mainly for discussion of the idea.

**Comment by annatuma** [comment]
This is on hold until we have more server resources. It'll be in the Parking Lot until we're ready.

**Comment by mathemancer** [comment]
Out of curiosity, do we have a ballpark on how many edges there would be in the graph we'd want to analyze?  There are some extremely efficient PageRank implementations available, including at least two that come out-of-the-box with Spark

**Comment by kgodey** [comment]
We haven't put any thought into this other than what's already here in the issue.

**Comment by kgodey** [comment]
We've determined that PageRank style algorithms are probably not going to be very effective for image search, so I'm closing this.
