### ISSUE TITLE
Create API endpoint for finding similar images

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#286]
The API endpoint should accept an image ID as input and provide a list of images that are similar to that image, probably using Elasticsearch's `more like this` query. 

In CC Search, this feature can be used to improve the the "related images" list on the image detail page.

**Comment by aldenstpage** [comment]
This is in dev for testing now. Example:

The original image: https://api-dev.creativecommons.engineering/image/ba17ec25-6230-4c14-b9d7-e95f3197ff5f
The related results: https://api-dev.creativecommons.engineering/image/related/ba17ec25-6230-4c14-b9d7-e95f3197ff5f
