### ISSUE TITLE
Investigate use of the BM25 algorithm to search image titles

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#288]
The similarity algorithm used to search titles was switched from BM25 to boolean in https://github.com/creativecommons/cccatalog-api/pull/281 to avoid ranking repeated words in titles higher.

We should investigate switching back to BM25 and set the `k1` tuning value to a low value just for the title field.

See https://github.com/creativecommons/cccatalog-api/pull/281#pullrequestreview-230833576 and [BM25 algorithm docs](https://www.elastic.co/guide/en/elasticsearch/guide/master/pluggable-similarites.html) for more info.

**Comment by annatuma** [comment]
@aldenstpage I'm putting this in Q2 of the backlog, given that there are other search algorithm improvements scheduled for then. Please evaluate if this is a fit for community contributions and if so, label it accordingly.
