### ISSUE TITLE
CC0 license URL is broken on image details endpoint

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-api#289]
In the response to `https://api-dev.creativecommons.engineering/image/75abec02-d1db-4d5f-90ee-cece6c2491ba` the  `license_url` comes with the value `https://creativecommons.org/licenses/cc0/1.0/`.

It should be ` https://creativecommons.org/publicdomain/zero/1.0/`.

This is what's causing https://github.com/creativecommons/cccatalog-frontend/issues/345

**Comment by aldenstpage** [comment]
I fixed this with a redirect

**Comment by aldenstpage** [comment]
https://creativecommons.org/licenses/cc0/1.0/ redirects to /publicdomain/zero/1.0 now. There was a rule for this already for /licenses/CC0/1.0/ already, but it wasn't case sensitive.
