### ISSUE TITLE
search phrase relevance example

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-api#291]
Feedback from a user on search phrases that are no longer returning specific, relevant results. This is just an example for us to test. Defer to @aldenstpage on how!

> For example, when I search for “bumblebee” + “Ontario” or bumblebee + Ontario bumblebees do come up but not specifically from Ontario, as they would have before. 
>  
> Or, I have recently searched for “Nature Day” + “Ottawa” and Nature Day + Ottawa, photographs from Ottawa came up but nothing to do with Nature Day or nature and not listed in any meaningful order.
>  
> As another example, when I typed Ontario + raptor + bird on the first page of suggested images raptors from other countries and provinces came up which are not found in Ontario, the leading term, so results can be quite confusing.

**Comment by aldenstpage** [comment]
Are you able to provide the full message from the user?

**Comment by aldenstpage** [comment]
I'd suggest the user tries using advanced querying, such as "ontario AND bumblebee", or "ontario AND raptor" (no quotes), which will more explicitly narrow down their search.

Additionally, when I search "ontario bumblebee", the first image I see is a bumblebee with the tag "ontario". It seems like the ranking is working as expected.

**Comment by janeatcc** [comment]
Leaving this closed but noting that this worked for the user. But I also added a note for adding advanced search tips to-do for front end on Teamweek.
