### ISSUE TITLE
Has the pagesize URL param been deprecated?

### ISSUE THREAD

**Issue by jumpinvestor** [creativecommons/cccatalog-api#298]
I'm using this URL to retrieve photos from the API:

https://api.creativecommons.engineering/image/search?q=beach&li=by,by-sa,cc0,pdm&page=1&pagesize=500

It works fine, with the exception of the "pagesize" param, which always only returns 20 results per page. I'd like to be able to return the max result set per request (500 from the docs) to cut down on the number of API calls. 

Has this param been deprecated, or is there a mistake in the request I'm using?

**Comment by aldenstpage** [comment]
Hi @jumpinvestor, `pagesize` works, but the server silently lowers the results to the default size (20) if the limit (499) is exceeded). Perhaps it would be better to throw a bad request error in this situation. Sorry about the slight delta between the docs and reality, I'll fix that.
