### ISSUE TITLE
Feature idea: Consider using oEmbed to make embedding even more simple

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-api#299]
oEmbed (https://oembed.com/) is a simple way to just copy/paste the URL of the page into your oEmbed ready tool to include image and proper attribution.

Is this on the roadmap?

**Comment by hedonhermdev** [comment]
Can I take up this issue? What exactly needs to be done?

**Comment by kgodey** [comment]
@hedonhermdev I just assigned you another issue, please do that first.

We need to add more detail to this issue.

**Comment by annatuma** [comment]
@aldenstpage please flesh this ticket out, and then open it up to community contribution. We're putting it in the current sprint for ticket work.

**Comment by aldenstpage** [comment]
This seems like it could be in tension with our desire to embed license attribution, which is not supported by oEmbed. Wouldn't we prefer if people used our own attribution blob with this information included? @sarahpearson?

In any case, this has been superseded by https://github.com/creativecommons/cccatalog-api/issues/445.
