### ISSUE TITLE
Initial work on CC-catalog API server (set up Django REST skeleton and migrate models from the legacy app)

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#3]

**Comment by pa-w** [comment]
Hey, @aldenstpage, can you point to the commits that were relevan to this issue?

**Comment by aldenstpage** [comment]
You can find most of it in the [es-sync branch](https://github.com/creativecommons/cccatalog-api/commit/d96a3af11d44c996e122741c66b7cfe0a2fcbc9b) that I've been working on, since all of this stuff was a prerequisite of working on the Elasticsearch synchronizer.

Apologies for the monster commit, I restructured the project and added a lot of new content at the same time.
