### ISSUE TITLE
Experiment with stemming and lemmatization algorithms

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#303]
- Measure the impact of different stemming and lemmatization algorithms on the relevance of search results.
- Run A/B tests to determine success.

**Comment by annatuma** [comment]
Per discussion, the impact of changes to stemming and lemmatization algorithms are likely to be much smaller than e.g. those search relevance changes tied to popularity or usage data. We're therefore not moving forward with any changes.
