### ISSUE TITLE
Return image ratio or width/height

### ISSUE THREAD

**Issue by borriglione** [creativecommons/cccatalog-api#306]
I'm a developer of tutory.de and we currently experiment to implement the creativecommons search into our OER editor.

As we are working with a grid-based editor and image placement it would be really helpful to know the image ratio or image width & image height for a search result before the image is really fetched.

Width & height were provided by Wikipediasearch, Flickr, Openclipart and Pixabay for example

**Comment by aldenstpage** [comment]
Hi @borriglione, we're going to implement this in the near term, but it will not be available 100% of the time since not all upstream sites provide resolution through their APIs. 

In the future, we'll scrape and analyze every image in our catalog before indexing it.

**Comment by aldenstpage** [comment]
You'll start seeing this data in production on Wednesday after we've reindexed our search results.
