### ISSUE TITLE
Create search result quality test cases

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#311]
- Decide on a set of search terms for us to evaluate changes to the search algorithms. These should be a combination of our top search terms and search terms that we have received critical user feedback about.
- Automate taking screenshots of this list of search terms so that we reduce manual QA work. New search terms should be able to be added easily.
- Mirror our production environment on ccsearch-dev

**Comment by aldenstpage** [comment]
Edited and added "Mirror our production environment on ccsearch-dev"

**Comment by aldenstpage** [comment]
Reopened while I dockerize this per @brenoferreira's request

**Comment by kgodey** [comment]
Reopening this because the PR is not yet merged.
