### ISSUE TITLE
Experiment with manual provider weighing

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#312]
- Experiment with weighing providers differently in search results.
- Run A/B tests to determine success.

**Comment by aldenstpage** [comment]
This is blocked until AWS supports Elasticsearch 7.x; we need the `rank_feature` field to implement this.

**Comment by aldenstpage** [comment]
7.x is generally available now so this is becoming a priority again

**Comment by kgodey** [comment]
That all makes sense. Do you want to proceed with manual provider weighing or abandon it? It seems like the effort might be better spent on prioritizing individual image popularity.

**Comment by aldenstpage** [comment]
Let's close this for now. We can use it as one factor among several once we have additional quality metrics available.
