### ISSUE TITLE
rawpixel catalog

### ISSUE THREAD

**Issue by rawpixel-vincent** [creativecommons/cccatalog-api#327]
**Is your feature request related to a problem? Please describe.**
It's difficult to find the public domain images rawpixel produced.

**Describe the solution you'd like**
We would love to see rawpixel listed with others catalogs in this section https://search.creativecommons.org/collections

**Comment by sclachar** [comment]
@aldenstpage & @kgodey 👆

**Comment by kgodey** [comment]
Moving this to the API repo since catalog work is done.

**Comment by kgodey** [comment]
The catalog work is done here, we just need to add it to the API and frontend.

**Comment by rawpixel-vincent** [comment]
Hi, thanks to take care of this, I noticed the list of providers here too https://search.creativecommons.org/about would be good to add rawpixel there too

**Comment by aldenstpage** [comment]
rawpixel was hidden due to https://github.com/creativecommons/cccatalog-frontend/issues/395; it shows up in the about page and search results now
