### ISSUE TITLE
Experiment with usage of popularity data in search algorithm

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#328]
- Use popularity metrics from https://github.com/creativecommons/cccatalog/issues/161 to rank search results.
- Run A/B tests to determine success.

We have some test popularity data available for Behance, I'd like to implement ranking by popularity using that (or mock data if it's not extensive enough) so it's ready to go once the data is available for other collections.

The expected outcome is that results from a provider will be influenced by popularity of results (likes, views, etc). Results with popularity data should not completely drown out providers where we don't have it.

- [ ] ~Copy test popularity data to intermediary database~ The sample data IDs don't line up with our production/dev IDs and isn't usable.
- [x] Index popularity data
- [x] Alter search algorithm to factor in popularity data

**Comment by aldenstpage** [comment]
This is blocked until AWS supports Elasticsearch 7.x; we need the `rank_feature` field to implement this.

**Comment by aldenstpage** [comment]
We have some test popularity data available for Behance, I'd like to implement ranking by popularity using that (or mock data if it's not extensive enough) so it's ready to go once the data is available for other collections.

The expected outcome is that results from a provider will be influenced by popularity of results (likes, views, etc). Results with popularity data should not completely drown out providers where we don't have it.

**Comment by aldenstpage** [comment]
We have the capability to index popularity data now (see https://github.com/creativecommons/cccatalog-api/pull/381) but need some production-quality data to make further progress.

**Comment by aldenstpage** [comment]
To be superseded with a more up-to-date issue
