### ISSUE TITLE
Audit current API and ensure it conforms to best practices

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#334]
This task is to review the current CC Catalog API schema and suggest changes that would put the API more in line with best practices.

Best practice guides:
- [White House Web API Standards](https://github.com/WhiteHouse/api-standards)
- [Best Practices for a Pragmatic RESTful API](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api)

**Comment by kgodey** [comment]
***Note**: These suggestions involve breaking changes. If we decide to implement the suggestions, I suggest we keep our current running version as-is and make these changes in a new version of the API (v1). We can then set a date for when we will stop supporting the current version and notify API users and ask them to switch to v1 by then.*

----

### Principles
I think we should commit to sticking to RESTful principles wherever possible ("pragmatic REST"). I also recommend sticking to the [White House Web API Standards](https://github.com/WhiteHouse/api-standards) because they're sensible.

### Suggested Changes – Standards
- We should have [RESTful URLs](https://github.com/WhiteHouse/api-standards#restful-urls). This means that our URLs should map to resource nouns and not include verbs and use HTTP verbs to operate on collections/elements.
     - We should have a single `/v1/images/` URL that encompasses all image operations. All image list operations should be handled by`/v1/images/` and all image detail operations should be handled by `/v1/images/<image_uuid>`
     - `/v1/images/` should return a list of images. If needed, we can have required parameters for this to match our current behavior of not providing a full list of images without some filtering applied.
     - The `image_browse` endpoint should be replaced by usage of `/v1/images/` with a `provider` URL parameter.
     -  The `image_search` endpoint should be replaced by usage of `/v1/images/` with appropriate URL parameters.
     - The `image_detail` endpoint should be replaced by usage of `/v1/images/<image_uuid>/`
     - The `image_related` endpoint should be replaced by usage of `/v1/images/ with a query parameter that takes the UUID of the image that results should be related to.
    - We should replace the `/image/statistics/` endpoint with just `/v1/statistics/` or if needed `/v1/statistics/images/`.
- Use [Versions](https://github.com/WhiteHouse/api-standards#versions)
    - Our documentation needs to be updated to use versioned URLs.
- Standardize responses
    - The replacements for the image list, image detail, and image search endpoints should all return the same representation of the image resource with the same fields.
    - All keys should always be returned, even if some values are null. e.g. we seem to skip the `creator_url` field altogther if it is not defined.
- Update [Error Handling](https://github.com/WhiteHouse/api-standards#error-handling)
    - We should have detailed error messages that provide the status, developer message, user message, and error code. The messages should support the ability to be translated (which makes the error code very important, we can identify errors easily even when we get translated error messages).
    - Each different type of error should have unique error codes and error messages.
- Improve metadata for resource lists (see [Metadata](https://github.com/WhiteHouse/api-standards#record-limits)
     - Show page size in metadata
     - Put all metadata inside a `metadata` key (page size, page count, total number of results).

### Suggested Changes – CC-specific
- Replace all usage of `provider` with `source`
    - This includes both the image and statistics endpoints
    - We should also not have duplicate `provider` and `source` fields.

**Comment by kgodey** [comment]
I'm still evaluating the authentication APIs and will post here when I have thoughts on those.

**Comment by brenoferreira** [comment]
# Query parameters

I prefer avoid using URL query parameters when a different URL endpoint can be used instead. For example:

> The image_browse endpoint should be replaced by usage of /v1/images/ with a provider URL parameter.

Do you mean something like `/v1/images/?provider=met`?
Why not something like `v1/images/provider/met`?

Same with the related images example. I'd prefer `v1/images/<uuid>/related`

# Statistics endpoint

About the `statistics` endpoint, can we change that? When I read `statistics` I think literally statistics about images. Can we change that to be `v1/providers` or something? Moreover, is that endpoint going to be responding with all the providers? Or in the future are we going to allow clients to request providers for a particular content type? Something like `v1/providers/images` and `v1/providers/oer` for example?

# Error handling

I don't particularly like a couple of things from the White House suggestion on error handling:

1. Sending the `status` code in the response payload. That's already provided in the HTTP response header for free.
2. I don't think we should include the `user message`. That's a frontend detail and responsibility. It can be internationalized for a particular location on the frontend, where in the API it would always be in English (if we don't internationalize the API). I'd prefer having only a `developerMessage`, which can be english only.

# Hypermedia

If we want to go fully RESTful, I think it would interesting to include hypermedia links on the metadata as well. For example in response to a search query:

`results: [ {title 'foo', id: 123, ...., details_endpoint: `http:/api.cc.org/image/123}]`

And in the image details endpoint
`{title 'foo', id: 123, ...., related_endpoint: `http:/api.cc.org/image/123/related}`

**Comment by aldenstpage** [comment]
We already make use of hypermedia - see `"detail":` field in the search endpoint. I agree it would be nice to have a link to related images in the detail page though.

**Comment by aldenstpage** [comment]
@kgodey,
>Note: These suggestions involve breaking changes. If we decide to implement the suggestions, I suggest we keep our current running version as-is and make these changes in a new version of the API (v1). We can then set a date for when we will stop supporting the current version and notify API users and ask them to switch to v1 by then.

We've warned downstream people about this on GitHub and through the semantic version.
>The API is still in semantic version 0.*.*, meaning the API can be changed without notice.

**Comment by aldenstpage** [comment]
After discussing this over the phone, it's clear that shutting off the 0.x version without a sunset period isn't an option, so we'll run it concurrently for the time being.

**Comment by kgodey** [comment]
To add to what @aldenstpage said, we will work with known API consumers to make sure they transition to the new API ASAP and then shut off the 0.x version.

**Comment by kgodey** [comment]
Responses to @brenoferreira 

> I prefer avoid using URL query parameters when a different URL endpoint can be used instead. For example:
> 
> > The image_browse endpoint should be replaced by usage of /v1/images/ with a provider URL parameter.
> 
> Do you mean something like `/v1/images/?provider=met`?
> Why not something like `v1/images/provider/met`?
> 
> Same with the related images example. I'd prefer `v1/images/<uuid>/related`

Breno and I discussed this on a call and concurred that `/v1/images/?provider=met` is a fine approach. We're still undecided on the structure of the related images URL, I think there's a reasonable argument to be made that "related" is not actually an intuitive filter since the API doesn't provide a list of images each image in related to. It's also reasonable that all lists of the image resource should be handled by the RESTful image endpoint, and "related" is not a noun.

Other opinions are welcome. I'll also do some more research.

> # Statistics endpoint
> 
> About the `statistics` endpoint, can we change that? When I read `statistics` I think literally statistics about images. Can we change that to be `v1/providers` or something? Moreover, is that endpoint going to be responding with all the providers? Or in the future are we going to allow clients to request providers for a particular content type? Something like `v1/providers/images` and `v1/providers/oer` for example?

I like `/v1/sources/`. Filtering sources by content types should be handled by query parameters.

> # Error handling
> 
> I don't particularly like a couple of things from the White House suggestion on error handling:
> 
>     1. Sending the `status` code in the response payload. That's already provided in the HTTP response header for free.
> 
>     2. I don't think we should include the `user message`. That's a frontend detail and responsibility. It can be internationalized for a particular location on the frontend, where in the API it would always be in English (if we don't internationalize the API). I'd prefer having only a `developerMessage`, which can be english only.
> 

This makes sense, we can get rid of those two fields.

> # Hypermedia
> 
> If we want to go fully RESTful, I think it would interesting to include hypermedia links on the metadata as well. For example in response to a search query:
> 
> `results: [ {title 'foo', id: 123, ...., details_endpoint: `http:/api.cc.org/image/123}]`
> 
> And in the image details endpoint
> `{title 'foo', id: 123, ...., related_endpoint: `http:/api.cc.org/image/123/related}`

I think it's fine for the image resource to include hypermedia links in the data. We should use the `detail_url` convention since I think that's more common than `_endpoint`.

**Comment by kgodey** [comment]
Response to @aldenstpage 

> We already make use of hypermedia - see `"detail":` field in the search endpoint. I agree it would be nice to have a link to related images in the detail page though. Agreed on your comment about the status code and error message handling as well.

The fields on the detail endpoint should not be any different from the image resource on the list endpoint (if my suggestion is implemented, anyway). So we should have the related image URL be present everywhere.

**Comment by kgodey** [comment]
Re: authentication

It seems like the most RESTful way to sign up for a token is to have an endpoint like `/v1/auth_tokens/`, which would replace `register_api_oauth2`. It would function the same way, although I think we should also return `description` and `email` in the response.

Similarly, ` /oauth2/key_info` should be renamed `/v1/rate_limit/`, like [GitHub's API](https://developer.github.com/v3/rate_limit/).

**Comment by kgodey** [comment]
@aldenstpage and I talked and decided that we'd go with `/v1/recommendations/` for the related endpoint. This is RESTful and will also allow us to expand to mixed media recommendations without changing the URL in the future (whereas `/v1/images/<uuid>/related/` restricts us to images).

**Comment by kgodey** [comment]
I'm going to close this since the audit is done. The spec and implementation will happen in #388.

**Comment by aldenstpage** [comment]
I turned this into a spec at #388. I omitted a few suggestions for the following reasons:

1. Changes to error handling; I'm with Breno, user-facing errors are a frontend concern.
2. We won't necessarily return a key when its value is `null`; this is dead weight in the response. Further, it's not universally agreed upon that you should include empty keys, so I'm not inclined to go through the trouble of changing this behavior. See [this discussion on StackOverflow](https://softwareengineering.stackexchange.com/questions/285010/null-vs-missing-key-in-rest-api-response) and the "further reading" section.
3. We'll switch to `limit` and `offset` style pagination. I'm not inclined to add a `metadata` section storing these values because there is no standard saying we need to do that; implementation details will vary between APIs.
4. We won't allow `/image/` to be used without query parameters because that's of no utility for image searching and a gift to scrapers.

**Comment by kgodey** [comment]
Looks good. Responses:

1. We should still update the error format to be standard in all cases (DRF has differing formats by default based on whether it is a "non field error" or not). We should also include a numerical error code (to identify the error easily; this is not the same as a HTTP status code) and developer message.

2. I am more persuaded by [this answer](https://stackoverflow.com/a/21201065). 
> The more public the API and and the more potential consumers of the API, the more invariant the API should be. 

I think it is also [more Pythonic ("explicit is better than implicit")](https://www.python.org/dev/peps/pep-0020/) to always return all keys.

3. Could you provide an example response? I'm not entirely clear on what this entails.

4. I think that's fine.

**Comment by aldenstpage** [comment]
I incorporated (2) into the spec ticket. Sorry that my response with (3) was confusing; I rewrote it; please see the example there.

>1. We should still update the error format to be standard in all cases (DRF has differing formats by default based on whether it is a "non field error" or not). We should also include a numerical error code (to identify the error easily; this is not the same as a HTTP status code) and developer message.

For (1), could you provide an example of an error that is not adequately communicated by status codes and the existing response body? For example, if a consumer specifies an invalid license type in their search parameters: https://api.creativecommons.engineering/image/search?q=test&lt=foo, they get back a validation error.
```
HTTP 400 Bad Request
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "validation_error": {
        "lt": [
            "License type 'foo' does not exist."
        ]
    }
}
```

Could you let me know, in this instance,
1. What should the error code be?
2. What does the error code tell us that `400 Bad Request` doesn't?
3. How will it help us or the user debug the problem?
4. What do you mean by "non-field" error? Do you mean something that would throw a `500 Internal Server Error`? I have the same questions as above in that case

**Comment by kgodey** [comment]
### Pagination
I think the pagination parameters you listed make sense. 

Are we also going to be using a `page_size` parameter? If we are, I'd prefer to use `page_size` instead of the current `pagesize` because I think it's more readable/consistent.

### Error Handling

I agree that error codes add some bureaucracy. DRF has an option for a [custom exception handler](https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling) that should make it easier.

Please see my answers to your questions below and let me know what you think (or ask more questions if needed).

(1) I was thinking the error code would be some sort of short unique identifier. A simple alpha/numeric string seems like the most readable thing.

(2) The error code would help developers identify the kind of error they had made. For example, if I omitted a required parameter, I would get error code A. If I instead provided an invalid value for a parameter, I would get error code B. Both of these would return `400 Bad Request`, though.

(3) Error codes would provide the developer with more granular errors. We could maintain documentation of what each error code and what it means. You could get some information from the error message strings, but I think it would be ideal to be able to change the error message strings while preserving the error code so that developers know it is the same error even though the message has changed.  When you just get a `400 Bad Request` or a `500 Internal Server Error`, you don't have as much information about what you did wrong. I think having error codes would improve the UX ([or DX](https://hackernoon.com/the-best-practices-for-a-great-developer-experience-dx-9036834382b0)) of the API.

(4) By `non_field_errors`, I mean (quoted from [this page](https://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views)):
> Validation errors are handled slightly differently, and will include the field names as the keys in the response. If the validation error was not specific to a particular field then it will use the "non_field_errors" key, or whatever string value has been set for the NON_FIELD_ERRORS_KEY setting.

e.g. going to https://api.creativecommons.engineering/image/search gives me:

```
{
    "validation_error": {
        "non_field_errors": [
            "You must use either the `q` parameter or an advanced searchparameter such as `title`, `tags`, or `creator`."
        ]
    }
}
```

I find DRF's default behavior here confusing. `non_field_errors` is a special key and that's not immediately apparent if you're not familiar with DRF. I don't think I've seen that in any other API. Even if we didn't do error codes, I'd advocate for changing this behavior.

(5) I've observed that a lot of API error responses and design recommendations are not nested to the extent that DRF does by default. Here are some links:

- [Twitter API error documentation](https://developer.twitter.com/en/docs/basics/response-codes), includes error codes documentation
- [Plaid API error documentation](https://plaid.com/docs/#errors-overview), note flat structure and error codes
- [Stripe API error documentation](https://stripe.com/docs/api/errors), note flat structure
- [GitHub API error documentation](https://developer.github.com/v3/#client-errors), note flat structure and error codes
- [Article on standardizing API error implementations](https://blog.restcase.com/rest-api-error-handling-problem-details-response/)
Plus the error handling sections of the [White House API standards](https://github.com/WhiteHouse/api-standards#error-handling) and [Best Practices for a Pragmatic RESTful API](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#errors)

**Comment by aldenstpage** [comment]
I do see where you're coming from with DRF's nested errors, which are ugly and maybe unnecessarily difficult to parse compared to a flat message, but they do get the job of communicating problems to callers done, and I would caution that overriding the batteries-included system is going to involve extra effort in testing, documentation, and time to implement, when the existing implementation is sufficient.

Separate from the error handling, some of the examples you pointed out earlier in the ticket reference operation IDs instead of endpoints (`image_detail` instead of `/image/{uuid}`), which I think lead to some confusion and requesting some changes that were already implemented in a RESTful manner. Operation IDs are an OpenAPI/Swagger concept; see [this reference](https://swagger.io/docs/specification/paths-and-operations/). If you scroll a bit further below the operation ID in the API documentation, you can see examples of the actual endpoints being called.

I'm already working on the `v1` implementation, there's plenty to do while we iron out these last details.

**Comment by brenoferreira** [comment]
As far as the errors are concerned, I think the HTTP status codes should be enough. We can send the `validation_error` on the response body with a more detailed error message in case of a `400 Bad Request` for example.

Our API is fairly simple, and not at all as complex as the Twitter and Stripe APIs for example, which have very complex validation systems and error handling. And keeping those error codes requires more active maintenance on documentation. If we keep the error messages descriptive enough, I think the error codes are probably unnecessary. At least for now.

Not sure about the Push API once we draft a spec for it

**Comment by kgodey** [comment]
#### Error Codes
Okay, those are good points. Let's not do error codes. If we decide to add them later, it would be an additive thing and wouldn't require any breaking changes anyway.

#### Nested vs. Flat Error Structure
I'm still on the fence about nested vs. flat errors, because changing the structure of the errors would be a breaking change and I think it would be good to get it right. @aldenstpage, could you see what it would take to implement a flat structure using the custom exception handler? If it's just a matter of implementing a single function, I think it's worth flattening the errors. If each error is going to have to have custom code applied to it, then it's probably not worth it.

#### Operation IDs
That makes sense, I was confusing the endpoint URL with the header in the documentation. This doesn't actually change the spec, right? Just makes some of the requested changes unnecessary.

**Comment by aldenstpage** [comment]
>Nested vs. Flat Error Structure

I'm happy to look into flattening the errors out, there's a good chance that DRF exposes those internals and that it won't be too difficult to implement.

>This doesn't actually change the spec, right? Just makes some of the requested changes unnecessary.
That's correct
