### ISSUE TITLE
Expose mature content flag data in API

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#339]
- Parse `mature={true|false}` from `meta_data` field in our database and set it as a field in Elasticsearch. Default to False if not defined.
- Add a `mature={true|false}` filter to the `/v1/images` endpoint

See https://github.com/creativecommons/cccatalog-frontend/issues/848 for implementation details.

**Comment by Sando1** [comment]
Hi I would like to work on this. Can you provide some description as to what I am supposed to so?

**Comment by aldenstpage** [comment]
I don't think this one is feasible to implement yet, we don't have any data indicating which works contain mature content, and generating that data is going to be a huge task.

**Comment by annatuma** [comment]
Related to https://github.com/creativecommons/cccatalog-frontend/issues/425

**Comment by josedavidb** [comment]
Hi! I can work in this issue? I can get more information about this?

**Comment by aldenstpage** [comment]
@Sando1 and @josedavidb, we've got a clearer picture of what our NSFW filtering scheme will look like now and have opened this up to community contribution if you're still interested. Thanks!

**Comment by jbasanta** [comment]
Yes! I'm still interested, I'm going to get into it!
