### ISSUE TITLE
Description field weighs duplicate words too heavily

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#355]
This is similar to an issue we had with titles; the `description` field should probably use boolean similarity instead of BM25. BM25 is more suitable for sifting through very long texts (like books) instead of brief metadata like ours. 

Related issue: https://github.com/creativecommons/cccatalog-api/pull/281#pullrequestreview-230833576

**Comment by Sando1** [comment]
Hi @aldenstpage! I would like to work on this. 
Just to recheck my understanding, we want to start using a boolean value instead of the value by BM25 but keep the BM25 value as well?

**Comment by aldenstpage** [comment]
We want the field to only use boolean similarity. See [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/similarity.html)

**Comment by Sando1** [comment]
Perfect. Thanks!

**Comment by aldenstpage** [comment]
Thank you!
