### ISSUE TITLE
Create group for API related emails to get sent to

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#357]
Currently, the API docs ask to email alden@ for help, we should set up a group that goes to you and me and use that as the email address instead for more redundancy and a shared record of API related requests. We should update the documentation to point to that group.

**Comment by aldenstpage** [comment]
Created a group at https://groups.google.com/a/creativecommons.org/forum/#!forum/ccsearch-api

It'll be linked in the API docs
