### ISSUE TITLE
Server throws 500 error when invalid query syntax is entered

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#363]
If you enter an unclosed bracket or a bang without a token (ex https://api.creativecommons.engineering/image/search?q=bye! or https://api.creativecommons.engineering/image/search?q=bye]), the query will fail with a 500 error.

These are special characters for performing advanced searches. The user should receive feedback about why their query failed. Pass the `RequestError(400, 'search_phase_execution_exception)` to the caller.

**Comment by Abhi-khandelwal** [comment]
@aldenstpage , Can I take this issue ?

**Comment by aldenstpage** [comment]
@Abhi-khandelwal Of course!

**Comment by krysal** [comment]
Hello, since has been no update in last 7 days, I would like to try resolve this issue.

**Comment by aldenstpage** [comment]
Feel free to take a look!

**Comment by ritesh-pandey** [comment]
@aldenstpage I have created a draft PR to understand if you wish to fix the issue in given manner. If draft looks okay, I would like to pick this up (only if we don't get response from @krysal )

I am new to Python to wanted to give it a try.

**Comment by krysal** [comment]
Seems like you solved this bug @ritesh-pandey so I think is okay if your PR is merged.

I would look around for another issue. @aldenstpage Do you suggest any other?

**Comment by aldenstpage** [comment]
Hi Krystal, I followed up with you on Slack - I recommend #294, it's a bit meatier of an issue so I would recommend implementing the first half of it for now, as listed below (I can handle authorization and authentication). I'm going to put together a few more outreachy-friendly tickets tomorrow also if you'd prefer to wait for a different issue to become available.

> Implement a DELETE /image/{uuid} call which removes an image from the API database and the search index, and sets the removed_from_source=True flag in the upstream catalog database.
