### ISSUE TITLE
INGEST_UPSTREAM API call hangs, breaking tests

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#369]
Ingestion Server is the component responsible for loading data from the catalog collection into the API and indexing the content into our search engine. It's kicked off by a call to a REST API.

`curl -XPOST localhost:8001/task -H "Content-Type: application/json" -d '{"model": "image", "action": "INGEST_UPSTREAM"}'`

When the command is received, the following takes place:
1. The data gets copied from the upstream catalog.
2. The data is cleaned, one row at a time, based on the rules in `cleanup.py`. The updated table becomes visible to production.
3. The data is indexed into Elasticsearch.

When running locally or in Travis, the server will sometimes get stuck after step 2 for unknown reasons - possibly some kind of race condition? It seems like it happens about 50% of the time.

**Comment by aldenstpage** [comment]
This seems like it only happens in `docker-compose`; it never happens in dev/production.

**Comment by kss682** [comment]
@aldenstpage @annatuma Can I work on this issue ?

**Comment by aldenstpage** [comment]
Please do!

**Comment by kss682** [comment]
@aldenstpage  where can I asks queries about it , here or in slack.

**Comment by kss682** [comment]
@aldenstpage  

```
ingestion-server_1  | [2020-03-04 15:06:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:13)
ingestion-server_1  | [2020-03-04 15:06:11 +0000] [13] [INFO] Worker exiting (pid: 13)
ingestion-server_1  | [2020-03-04 15:06:12 +0000] [49] [INFO] Booting worker with pid: 49
```
 Is this the error in the logs while running docker compose up.

**Comment by aldenstpage** [comment]
This is excellent, I didn't notice the worker timeout. That suggests that one of the endpoints in ingestion-server are hanging (see `api.py`). The next step is to figure out which endpoint it is that's timing out and why.

**Comment by kss682** [comment]
So I checked the logs again it seems that the time out is happening after indexing but before it could return worker_finished status .

```
indexer.py:255 - Pushing 4999 docs to Elasticsearch.
indexer-worker      | 2020-03-04 15:05:44,722 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.477s]
indexer-worker      | 2020-03-04 15:05:44,741 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.464s]
indexer-worker      | 2020-03-04 15:05:44,803 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.595s]
indexer-worker      | 2020-03-04 15:05:44,804 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.478s]
indexer-worker      | 2020-03-04 15:05:45,416 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.601s]
indexer-worker      | 2020-03-04 15:05:45,422 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.695s]
indexer-worker      | 2020-03-04 15:05:45,432 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.680s]
indexer-worker      | 2020-03-04 15:05:45,505 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.675s]
indexer-worker      | 2020-03-04 15:05:45,865 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.445s]
indexer-worker      | 2020-03-04 15:05:45,877 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.451s]
indexer-worker      | 2020-03-04 15:05:45,885 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.373s]
indexer-worker      | 2020-03-04 15:05:45,900 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.376s]
indexer-worker      | 2020-03-04 15:05:46,041 INFO base.py:122 - POST http://es:9200/_bulk [status:200 request:0.171s]
indexer-worker      | 2020-03-04 15:05:46,134 INFO indexer.py:262 - Elasticsearch up: batch_size=4999, uploaded_per_second=2549.2322568981212
indexer-worker      | 2020-03-04 15:05:46,159 INFO indexer.py:270 - Synchronized 5000 from table 'image' to Elasticsearch
indexer-worker      | 2020-03-04 15:05:46,192 INFO indexer_worker.py:68 - Notifying http://172.18.0.10:8001/worker_finished
ingestion-server_1  | [2020-03-04 15:06:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:13)
ingestion-server_1  | [2020-03-04 15:06:11 +0000] [13] [INFO] Worker exiting (pid: 13)
ingestion-server_1  | [2020-03-04 15:06:12 +0000] [49] [INFO] Booting worker with pid: 49
```

**Comment by kss682** [comment]
@aldenstpage So I was looking at the logs and code , the /worker_finished api is called, this is where the timeout is occuring , state.py is waiting for the file lock to be acquired .
When no time out.
```
indexer-worker      | 2020-03-04 14:43:37,066 INFO indexer_worker.py:68 - Notifying http://172.18.0.10:8001/worker_finished
ingestion-server_1  | 2020-03-04 14:43:37,071 INFO filelock.py:274 - Lock 140246669322704 acquired on lock
ingestion-server_1  | 2020-03-04 14:43:37,072 INFO state.py:67 - Received worker_finished signal from 172.18.0.9
ingestion-server_1  | 2020-03-04 14:43:37,114 INFO filelock.py:318 - Lock 140246669322704 released on lock

```

when there is timeout 

```
indexer-worker      | 2020-03-04 15:05:46,192 INFO indexer_worker.py:68 - Notifying http://172.18.0.10:8001/worker_finished
ingestion-server_1  | [2020-03-04 15:06:11 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:13)
ingestion-server_1  | [2020-03-04 15:06:11 +0000] [13] [INFO] Worker exiting (pid: 13)
ingestion-server_1  | [2020-03-04 15:06:12 +0000] [49] [INFO] Booting worker with pid: 49
ingestion-server_1  | 2020-03-04 15:06:19,390 INFO filelock.py:274 - Lock 140246669326864 acquired on lock
ingestion-server_1  | 2020-03-04 15:06:19,398 INFO state.py:67 - Received worker_finished signal from 172.18.0.9
ingestion-server_1  | 2020-03-04 15:06:19,423 INFO filelock.py:318 - Lock 140246669326864 released on lock

```

**Comment by aldenstpage** [comment]
This seems like a separate problem; I haven't seen the timeout occur after indexing has completed. You might have some corrupt state. Try `docker-compose down -v` and then `docker-compose up --build` before running further tests. This cleans up databases and rebuilds the project. You should do this every time you do `git pull`.

**Comment by kss682** [comment]
@aldenstpage  Yeah, looks like the timing out was local issue and it only occured once .  So I ran it around 10 times and it was completing , I was not able to reproduce the problem . 
So this should be the place where it is hanging 
 https://github.com/creativecommons/cccatalog-api/blob/16252c2a5f085217741571331d7abde315e46857/ingestion_server/ingestion_server/ingest.py#L268-L270

But it looks fine .

**Comment by aldenstpage** [comment]
It's not quite an issue local to me – even after switching to several new computers, I will occasionally run into this bug. Worst of all, it will sometimes kill the Travis build. I will say that how often it happens is highly variable to each machine.

**Comment by kss682** [comment]
@aldenstpage Ohh.., I am new to this , so can this be some factors totally unrelated to the code.

**Comment by kss682** [comment]
I ran ./load_sample_data.sh multiple times and the first time It got hung at clean.py , then onwards it's getting stuck at 

```
upstream_db_1       | 2020-03-07 08:44:51.525 UTC [729] CONTEXT:  COPY image, line 2
upstream_db_1       | 2020-03-07 08:44:51.525 UTC [729] STATEMENT:  COPY  image ( id,created_on,updated_on,identifier,provider,source,foreign_identifier,foreign_landing_url,url,thumbnail,width,height,filesize,license,license_version,creator,creator_url,title,tags_list,last_synced_with_source,removed_from_source,meta_data,tags,watermarked,view_count ) FROM STDIN with csv header



```
when load_sample_data tries to create the table it errors as it already exists.

**Comment by aldenstpage** [comment]
Adding "urgent" because this is becoming a major nuisance

**Comment by aldenstpage** [comment]
This appears to be fixed by https://github.com/creativecommons/cccatalog-api/pull/595. My suspicion here is that it's a docker-compose bug fixed by a subsequent version.
