### ISSUE TITLE
Version the API via URL path

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#376]
e.g. `https://api.creativecommons.engineering/v2/. . .`

It should be kept in line with the semantic version. Right now we're in 0.x.x

Existing URL paths should be redirected to void breaking API clients. We should probably remove them at some point so that we don't have to maintain them (since we're still not at v1, I feel comfortable doing that)

**Comment by annatuma** [comment]
@aldenstpage please add more detail to the ticket before you start work on this. Added to the sprint that starts on Monday. Thanks!

**Comment by kgodey** [comment]
Existing URL paths should be redirected to void breaking API clients. We should probably deprecate them at some point so that we don't have to maintain them (since we're still not at v1, I feel comfortable doing that).

**Comment by aldenstpage** [comment]
I've switched on URL path versioning. I don't think there's any more action to take since there aren't we aren't making any backwards-incompatible changes yet (the API still serves requests without a version string in the path). See commit https://github.com/creativecommons/cccatalog-api/commit/b5d0fecbbb342525d17ae70692f4868efb9bab16

See https://www.django-rest-framework.org/api-guide/versioning/ for more details; DRF will pass us a `version` string when a client uses it.
