### ISSUE TITLE
Link to PDM License is Broken

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#384]
CC Search includes works that have the Public Domain Mark, such as: 
https://search.creativecommons.org/photos/f798c858-a7af-4a3e-b2b7-a40a0a6780f5

The link to CC PDM 1.0, from both the Image Attribution and License section, goes here:
https://creativecommons.org/licenses/PDM/1.0/?ref=ccsearch&atype=rich

That's an Error page.

We believe those links should be updated to go here instead:
https://creativecommons.org/publicdomain/mark/1.0/ 

This may be something that needs to be fixed at the catalog level, or in the frontend, depending on where we're pulling license info URL data from.

**Comment by sarahpearson** [comment]
@annatuma That is, in fact, the deed for the Public Domain Mark.

**Comment by aldenstpage** [comment]
Fixed in the latest production release
