### ISSUE TITLE
Implement API updates described in #334

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#388]
### Versioning
All paths will be prefixed with `/v1/`. See 0.x.x support and sunset period.

### Use more RESTful URL paths

- [x] We should have a single `/v1/images/ `URL that encompasses all image operations. All image list operations should be handled by `/v1/images/` and all image detail operations should be handled by `/v1/images/<image_uuid>`
- [x] `/image/browse/{uuid}` should be replaced by `/v1/images?source={source}`
- [x] `/image/related/{uuid}` will be replaced with `/v1/recommendations/images/{uuid}`
- [x] ~Breaking with RESTful norms, `/images` without search parameters will return a `400 Bad Request`; this provides no utility to searchers and lots of value to people who want to scrape our entire database.~ Removed; only the first few thousand results can be retrieved, which means this won't be useful for scraping everything.

### Standardize responses
- [x] The replacements for the image list, image detail, and image search endpoints should all return the same representation of the image resource with the same fields.
- [x] Show `page_size` in search result responses.
- [x] Make greater use of hypermedia. For instance, image detail results will return a link to `/v1/recommendations/{identifier}`.
- [x] In all endpoints, whenever a field value is missing, it will show up as `null` in the response body, instead of being omitted.

### Miscellaneous
- [x] `/statistics/image` will be replaced by `/v1/sources/<content type>`.
- [x] `oauth2/key_info` will be replaced by `/v1/rate_limit/`.
- [x] `lt` and `li` search parameters will be replaced with the more legible `license_type` and `license` params.
- [x] Reformat error messages to be flat
- [x] All references to `pagesize` will be replaced with `page_size`.
- [x] To prevent subtle client-side bugs, using deprecated parameters in calls to `v1` should result in an exception being thrown. Deprecated parameters include `li`, `lt`, `pagesize`, and `provider`.
### 0.x.x support and sunset period
- [x] The API will continue to answer requests without a `/v1/` prefix; we should set a sunset period (I propose 6 months) to give clients time to migrate.

**Comment by annatuma** [comment]
A meeting to discuss suggestions made in the Audit ticket (https://github.com/creativecommons/cccatalog-api/issues/334) is needed before the description for this ticket can be written.

Kriti will write the description. Once this ticket is ready to be worked on, it will be implemented by Alden.

**Comment by aldenstpage** [comment]
I added a description to the ticket.
