### ISSUE TITLE
Feed attribution logs to analytics server

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#393]
We're able to get a rough idea of how often a work is given attribution in the wild by seeing how often our license SVGs get used and reading referral headers from server logs. This should be fed into our analytics API somehow for long-term storage.

No personal information will be stored; this will only allow us to track what domains have embedded CC Search attribution information (e.g. we will be able to say "moodle.org has 50,000 pages with a CC work on it and 300,000 people viewed them). This won't even tell us which works are receiving attribution.

**Comment by kgodey** [comment]
>  This won't even tell us which works are receiving attribution.

I think this would be good information to store, it might help our search algorithm.

**Comment by aldenstpage** [comment]
We're not able to tell what work has been embedded based on the server logs, only that a work is present. We could dispatch a crawler and parse the HTML to find what was embedded, but that's out of scope for what we're doing here - additionally, plenty of the URLs require authentication to access (e.g. logging into a university course) so we don't have any visibility of which work is out there.

**Comment by aldenstpage** [comment]
@kgodey, after giving this a fresh look, if knowing exactly which work is being attributed is valuable, we could figure this out in a low effort way by tacking on a query parameter in the attribution text. cc @zackkrida 

For example, let's say we're producing the attribution HTML for [this dog picture](https://search.creativecommons.org/photos/a3565050-50dc-4a57-8986-dc6bc3d8af48) with id=a3565050-50dc-4a57-8986-dc6bc3d8af48.
What we embed now:
`search.creativecommons.org/static/img/cc-by_icon.svg`

What we could embed instead:
`search.creativecommons.org/static/img/cc-by_icon.svg?identifier=a3565050-50dc-4a57-8986-dc6bc3d8af48`

The only downside I can think of is that privacy conscious users are sometimes a little sensitive about spooky looking UUIDs in URLs, but ultimately we are only tracking the work itself and not user data. It will also make the attribution text larger.

**Comment by aldenstpage** [comment]
Perfect. I'm going to look for the `image_id` parameter in attribution logs then. There's no rush to implement that, attribution logging will continue to work without it.

**Comment by kgodey** [comment]
This plan sounds good to me.
