### ISSUE TITLE
Missing license_version breaks search views

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#400]
Some images don't have a `license_version` defined. These are problematic, because we need to know the exact license to link to for attribution purposes. The API always expects the license version to be present and views without it will crash when an incomplete entry is in the results.

We should address this in the data layer, either by filling in the missing data or by culling entries where the full license information is unknown, but in the meantime the API needs to handle the missing data gracefully.

FYI @mathemancer

**Comment by annatuma** [comment]
Related: https://github.com/creativecommons/cccatalog-frontend/issues/299 (still planning to get the correct data from Science Museum).
