### ISSUE TITLE
Document error schemas

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#405]
In API v1, we override a lot of the default behavior for exceptions in Django REST Framework. The possible error responses should be clearly defined in our OpenAPI so consumers can anticipate the situations that they will arise. This should cover validation error and error 500s in particular.

See the `@swagger_auto_schema` decorator in `image_views.py` for an example of how this is done. The simplest way is to define Django Rest Framework serializers that match the structure of the error messages.

**Comment by ShraddhaAg** [comment]
Hi. I'm new to the community. Can I take this up? Thanks :)

**Comment by aldenstpage** [comment]
Yes, please feel free to take it on.

**Comment by Vineet-Sharma29** [comment]
@ShraddhaAg are you still working on this issue?

**Comment by ShraddhaAg** [comment]
@Vineet-Sharma29 feel free to take it up.

**Comment by keshav2212** [comment]
@Vineet-Sharma29 are you working on it ?

**Comment by Vineet-Sharma29** [comment]
@keshav2212 yes

**Comment by Vineet-Sharma29** [comment]
@aldenstpage Can you please give some guidance on this issue?

**Comment by aldenstpage** [comment]
While the errors are handled already, they are not documented in our OpenAPI schema, meaning that downstream users of the API cannot predict what will happen if they put in bad input. I suggest inducing some of the errors enumerated in https://github.com/creativecommons/cccatalog-api/blob/master/cccatalog-api/cccatalog/api/serializers/image_serializers.py, for example, and then seeing if there is a way to get them inside of our [drf-yasg](https://github.com/axnsan12/drf-yasg) schema.

**Comment by kss682** [comment]
Hi, can I work on this issue , if it's still open

**Comment by kgodey** [comment]
@Vineet-Sharma29 are you working on this?

**Comment by Vineet-Sharma29** [comment]
@kgodey yes

**Comment by gabbyprecious** [comment]
I would love to work on this, should I send a pull request?

**Comment by rohitgeddam** [comment]
Look like no one is working on this issue. Can i take this up

**Comment by kgodey** [comment]
go ahead @rohitgeddam

**Comment by ariessa** [comment]
@kgodey Actually, I've added error schemas in this closed PR #640

**Comment by kgodey** [comment]
Thanks @ariessa, closing this.
