### ISSUE TITLE
Minimal front-end for cccatalog

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#41]

**Comment by pa-w** [comment]
Can we break this down into smaller tasks? @sebworks @aldenstpage

**Comment by sebworks** [comment]
Yep @pa-w , I'll break this down.

**Comment by sebworks** [comment]
This task is composed of the following tasks:

- [ ] https://github.com/creativecommons/cccatalog-frontend/issues/1
- [ ] https://github.com/creativecommons/cccatalog-frontend/issues/2
- [ ] https://github.com/creativecommons/cccatalog-frontend/issues/3
- [ ] https://github.com/creativecommons/cccatalog-frontend/issues/6
