### ISSUE TITLE
Query string parser is too strict

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#410]
Any time a user unknowingly introduces a special character without a match (e.g. a colon, or a closing bracket), their query will fail. We should switch to `simple_query_string` instead of `query_string`, per the Elasticsearch team's recommendation.

> Because it returns an error for any invalid syntax, we don’t recommend using the query_string query for search boxes.
> 
> If you don’t need to support a query syntax, consider using the match query. If you need the features of a query syntax, use the simple_query_string query, which is less strict.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by gauravahlawat81** [comment]
Hey,can I take this issue ?

**Comment by gauravahlawat81** [comment]
`Starting cccatalog-api_db_1 ... error

ERROR: for cccatalog-api_db_1  Cannot start service db: driver failed programming external connectivity on endpoint cccatalog-api_db_1 (25c4c8e7e72ffc591d3a1bfb1cb3b3b2363c2e6b6e2392075a5bd29f74ae7005): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint cccatalog-api_db_1 (25c4c8e7e72ffc591d3a1bfb1cb3b3b2363c2e6b6e2392075a5bd29f74ae7005): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.`
i am getting this error while I ran `docker-compose up`. Any idea how to resolve this or what might be causing this issue ?

**Comment by gauravahlawat81** [comment]
I just googled for this issue, Port 5432 is used by PostgresQL and Docker also was trying to use the same port. I don't have any errors as of now, sorry for troubling you.

**Comment by gauravahlawat81** [comment]
By the way, can you tell me how can I reproduce this error ?

**Comment by aldenstpage** [comment]
Hi @gauravahlawat81, feel free to take a look. You can reproduce this error by using query string syntax incorrectly. For example, you can have a trailing exclamation point, or an unclosed bracket. The query "hello!" would trigger this error.

**Comment by madewithkode** [comment]
Hi @aldenstpage, it'd be nice to add the "in progress" label to this issue if truly @gauravahlawat81 is working on it, in order to avoid more interests on same issue.

**Comment by gauravahlawat81** [comment]
Hey, I am extremely sorry. I have my mid term exams coming up so I wouldn't be able to work on this issue. It's fine if someone else wants to take it.

**Comment by madewithkode** [comment]
It's all good man, best of luck in your exams. I'd try to understand the
problem more to see if I'd work on it.
