### ISSUE TITLE
Put AWS Architecture Documentation in Wiki (or at least links to documentation)

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#412]
Creative Commons received an [AWS Imagine grant](https://opensource.creativecommons.org/blog/entries/aws_grant/). We should document the proposal in the wiki.

It should include complete documentation, including from grant proposal and https://github.com/creativecommons/cccatalog-api/issues/398

**Comment by aldenstpage** [comment]
https://wikijs.creativecommons.org/aws-imagine-grant

**Comment by kgodey** [comment]
@aldenstpage I moved this to https://wikijs.creativecommons.org/tech/aws-imagine-grant, it should be under the tech namespace.
