### ISSUE TITLE
Add standard deprecation message to v0 API responses

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#414]
Add a warning in all v0 API responses that suggests that users migrate to v1. We anticipate that we will be shutting down the API at the end of July. The shutdown date should be included in both the deprecation message and the API responses.

**Comment by annatuma** [comment]
Also, don't forget to update the documentation accordingly.

**Comment by DantrazTrev** [comment]
Is this issue open for work ? if it is what shutdown date should be included?
