### ISSUE TITLE
Update how API serves License URL to frontend

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#415]
We need to update how the API serves the license URL to the frontend.

We are now (or about to) adding the License URL to metadata, instead of just license information. Therefore the API should (likely) serve that license URL when available, else continue to construct license URL based on license info (when URL not present in metadata).

Store the direct link to the license in `license_url` in the `meta_data` column. We should still populate `license` and `license_version` in cases where we provide a direct link.

**Comment by annatuma** [comment]
@mathemancer and @aldenstpage to discuss and update description with exactly what/how we'll change things.

**Comment by aldenstpage** [comment]
This seems like a good way to solve the issue with international jurisdictions. I would propose that we add an optional `license_url` to the `meta_data` column just as the description says.

**Comment by kgodey** [comment]
@aldenstpage please edit the ticket description to contain all details, then we can move to ready.
