### ISSUE TITLE
Remove references to provider in /source endpoint

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#421]
In version 1.0 of the API, we intended to remove all references to "providers" and replace them with `source`. In `/v1/sources`, you can see that we missed a spot. Change `provider_name` and `provider_url` to `source_name` and `source_url` in the response for this endpoint.

For example, this is what the current result looks like:
```GET /v1/sources

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "provider_name": "thorvaldsensmuseum",
        "image_count": 8912,
        "display_name": "Thorvaldsens Museum",
        "provider_url": "http://www.thorvaldsensmuseum.dk"
    },
    . . .
```
This is what we want:

```


GET /v1/sources

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "source_name": "thorvaldsensmuseum",
        "image_count": 8912,
        "display_name": "Thorvaldsens Museum",
        "source_url": "http://www.thorvaldsensmuseum.dk"
    },
    . . .
```

**Comment by khyati-agarwalss** [comment]
Hi @aldenstpage 
I would like to work on this issue.

**Comment by anoited007** [comment]
@khyati-agarwalss are you still working on this issue?

**Comment by khyati-agarwalss** [comment]
> @khyati-agarwalss are you still working on this issue?

Yes

**Comment by DantrazTrev** [comment]
Hey @khyati-agarwalss are you still working in this issue?

**Comment by khyati-agarwalss** [comment]
> Hey @khyati-agarwalss are you still working in this issue?

No, you can proceed with it

**Comment by DantrazTrev** [comment]
Hi @aldenstpage I've changed the name but only at the endpoint , does this issue requires internal var changes?

**Comment by cristomathew** [comment]
is this issue still open if so can i start working on it?

**Comment by DantrazTrev** [comment]
Hey @aldenstpage I've made the changes
