### ISSUE TITLE
Auto correct feature in CC Search

### ISSUE THREAD

**Issue by nishantsethi** [creativecommons/cccatalog-api#427]
As the CC Search has just got out of beta and is now public, there should be an autocorrect option so that if a user has by chance entered the spelling of a word wrong, an option to correct it, could be displayed.

For now, a dictionary can be made(js or any other language) and the text can be checked for errors before sending the API request. 

The output of the auto correct could be something like this -
![ffg](https://user-images.githubusercontent.com/19774313/57024132-79048180-6c51-11e9-9654-8303ee96e94a.jpg)

**Comment by scheleon** [comment]
Well, we can keep separate dictionaries for different languages, then using the user's requested language provide suggestions.

**Comment by kgodey** [comment]
@aldenstpage if this would be a good API endpoint, could you please define the ticket better for what the endpoint should look like and then open it up to the community?

**Comment by aldenstpage** [comment]
You're correct that this is best suited as an API endpoint. I've opened up a more detailed ticket here: https://github.com/creativecommons/cccatalog-api/issues/429
