### ISSUE TITLE
Implement "did you mean. . ." corrections in /v1/images endpoint

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#429]
Return a `suggestions` field in queries to `/v1/images`.

Example request and response:
`GET /v1/images?dags`
```
{
  "suggestions": "dogs" 
   "result_count" : 10000,
   "results" : [
      {
         "license_version" : "2.0",
         "foreign_landing_url" : "https://www.flickr.com/photos/48889073020@N01/3042355",
         "title" : "Big Dog, Little Dog",
         "detail_url" : "https://api.creativecommons.engineering/v1/images/3474484f-f75c-45bd-85f7-0efa8678bc1a",
         "width" : 500,
         "height" : 375,
         "url" : "https://farm1.staticflickr.com/3/3042355_c700071469.jpg",
         "thumbnail" : "https://farm1.staticflickr.com/3/3042355_c700071469_m.jpg",
         "related_url" : "https://api.creativecommons.engineering/v1/recommendations/images/3474484f-f75c-45bd-85f7-0efa8678bc1a",
         "license_url" : "https://creativecommons.org/licenses/by-nc-nd/2.0/",
         "source" : "flickr",
         "fields_matched" : [
            "description",
            "tags.name",
            "title"
         ],
         "id" : "3474484f-f75c-45bd-85f7-0efa8678bc1a",
         "tags" : [
            {
               "name" : "molly"
            },
. . .
```

The following modifications will need to be made:
- Update `search_controller` to use `suggesters`. See the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html) for information on how this feature works.
- Update the Image serializer to return the `suggestions` field.

Whether the search should be repeated again with the suggested term is left at the discretion of the client; we should only return the suggestions and not repeat the search.

We will use this to implement spelling corrections on the front end.
![Autocomplete](https://user-images.githubusercontent.com/19774313/57024132-79048180-6c51-11e9-9654-8303ee96e94a.jpg)

**Comment by AyanChoudhary** [comment]
can I take up this issue?

**Comment by kgodey** [comment]
@AyanChoudhary go ahead.
