### ISSUE TITLE
dev build throwing CORS errors and blocks queries after a while

### ISSUE THREAD

**Issue by Mahelaa** [creativecommons/cccatalog-api#433]
## Describe the bug
Working on a feature for the cccatalog-frontend build on my local machine and a number of Cross-Origin Request Blocked errors appear. Search queries work fine for about a day and afterwards blocks all my requests. and therefore does not allow any search to go through. Search works fine on the main website https://ccsearch.creativecommons.org/ with no CORS errror.(concluding my ip wasnt filtered)

## To Reproduce
1. Clone cccatalog-frontend
2. npm install and run dev
3. open on browser and inspect element

![Screen Shot 2020-02-26 at 10 29 18 AM](https://user-images.githubusercontent.com/25326308/75313483-f7867b80-5882-11ea-975f-da7cc5405817.png)

Captured on a freshly cloned repo

![Screen Shot 2020-02-26 at 10 32 55 AM](https://user-images.githubusercontent.com/25326308/75313657-74b1f080-5883-11ea-8e43-03e8f291d12a.png)

Old repo with modifed code

## Expected behavior
Allow any search to go through without issues

## Debug
Tried a new clone and cors still exists but allows to search
Restarted my browser and also tried on different networks

## Desktop 
 - OS: MacOSX 10.15 Catalina
 - Browser Firefox
 - Version (73)

## Additional context
Ive run across this issue once before on my NodeJS server and i bypassed this by including
`const cors = require('cors');
app.use(cors());`

**Comment by aldenstpage** [comment]
This is a client-side issue; I recommend disabling CORS support in your browser while working with the search engine locally. There's a good guide for achieving that in Chrome [here](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome). Of course, you should leave CORS on for your normal browsing :)
