### ISSUE TITLE
serializers defined in views inspite of having separate serailizers.py files

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-api#437]
## Describe the bug
In `link_views.py` and `list_views.py`, serializers `_LinkCreatedResponse` and `_CreateResponse` have been defined respectively. These two files can be refactored in such a way that the serializers are defined in their appropriate serializer file

## Additional context
Would like to work on this issue. Can CC team approve and assign this issue to me?

**Comment by kgodey** [comment]
@aldenstpage

**Comment by aldenstpage** [comment]
Those serializers are response stubs – they model responses for the documentation, which are generated by views. The decision to include them in the views was a conscious one.
