### ISSUE TITLE
Hide the thumbnail proxy from end-users

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#444]
To generate our own thumbnails, we route images through a thumbnail proxy. For example:

Request:
```
GET https://api.creativecommons.engineering/v1/images?q=friday
```
Response:
```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "result_count": 10000,
    "page_count": 250,
    "page_size": 20,
    "results": [
        {
. . .
            "thumbnail": "https://api.creativecommons.engineering/t/600/https://farm8.staticflickr.com/7623/17091223342_6cf62e6789_m.jpg",
. . . 
```

Instead of returning a direct link to the thumbnail proxy, we should return a direct link to an image in our infrastructure, similar to this: `https://api.creativecommons.engineering/v1/thumbs/6eca723c-0ac4-4de6-b83f-96812de61441.jpg`. Internally, when the image is requested from the `/v1/thumbs` endpoint, the API server will parse the UUID from the URL, look up the URL of the underlying image in our database using the UUID, pull the image from the thumbnail proxy, and return it at the requested URL.

Here's how it works now:
![Thumbnail proxying part 1](https://i.imgur.com/ExHLxYc.png)

Here's what we want:
![Thumbnail proxying part 2](https://i.imgur.com/O8ljhWh.png)

This is important because it allows us to not have to worry about securing our thumbnail proxy. It will have a positive impact on the CC Search Browser Extension (or anyone else that needs to embed our thumbnails), which currently cannot access the thumbnailing proxy due to [`referer` header security restrictions](https://github.com/willnorris/imageproxy#allowed-referrer-list). It is not tenable for us to disable `referer` restrictions because that would allow malicious users to route images from outside of CC Search through our proxy.

This is open for community contributions, but not recommended for developers that are not familiar with Django and general backend development. The thumbnail proxy is included in the `docker-compose` file, so it should be easy to test your solution locally. Please do not ask for permission to work on the issue; if you are interested, announce your intent here, check out a new branch and get started.

**Comment by sp35** [comment]
Interested, I'll start as soon as I get free from my last mid-sem exam today.

**Comment by avivith** [comment]
Hi. Can I work on this issue?

**Comment by krysal** [comment]
Hi @avivith, as README says:
> You are welcome to take any open issue in the tracker labeled 'help wanted' or 'good first issue'; **there's no need to ask for permission in advance**.

But it's good that you announce that will be working on it!

**Comment by hedonhermdev** [comment]
Hello, the previous PR on the issue seems to have become stale. Can I continue the work on this issue?

**Comment by aldenstpage** [comment]
Hi @hedonhermdev, it's not stale so much as pending additional testing and review. I think it provides a strong enough base that redoing this is not necessary.

**Comment by hedonhermdev** [comment]
Okay, let me know if there is any work that needs to be done

**Comment by CeRKeZ55** [comment]
Yes finish it

Mvg, Yusuf Soysal
Directeur Soysaltech

Op 5 mei 2020 om 12:36 heeft Tirth Jain <notifications@github.com> het volgende geschreven:

﻿

Hello, the previous PR on the issue seems to have become stale. Can I continue the work on this issue?
