### ISSUE TITLE
Implement oEmbed endpoint

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#445]
https://ombed.com
>oEmbed is a format for allowing an embedded representation of a URL on third party sites. The simple API allows a website to display embedded content (such as photos or videos) when a user posts a link to that resource, without having to parse the resource directly.

To support oEmbed, we are going to need to implement an API endpoint at `/v1/oembed`, which will accept parameters `url` and `format`. Fully implement the specification **except for wildcards**. Right now, we only have photos, so only implement the `photo` type. We want to support both JSON and XML formats (this should be as simple as switching Django renderers). Most importantly, we want to add a `license_url` field to the response, which will link to the CC License for an embedded image.

oEmbed requires a `height` and `width` field for images. In some cases, we don't know the dimensions of an image. In those cases, the `oEmbed` endpoint should load the image server-side and measure the dimensions before returning the fully populated response.

The endpoint must be cleanly represented in our generated documentation. There should be some unit tests demonstrating that the endpoint works as expected.

Example request:
GET `https://api.creativecommons.engineering/v1/oembed/?format=json&url=https%3A//search.creativecommons.org/photos/f5af4a72-9ab2-4f5a-a0c5-090e7350c209`

Response:
```
{
  "version": "1.0",
  "type": "photo",
  "width": 1024,
  "height": 768,
  "title": "kittens 022",
  "author_name": "bytehead",
  "author_url": "https://www.flickr.com/photos/66884677@N00",
  "license_url": "https://creativecommons.org/licenses/by-sa/2.0/"
}
```

We would also like to use the `html` field (normally not required for `photo` types) to embed additional rich attribution information as we do in the CC Search front end (optional for contributors; we can add this ourselves).

**Comment by mzeinstra** [comment]
I did a project embedr (https://www.kl.nl/en/projects/embedr-image-embedding-done-right/ ) where we only used CC-licensed material, we used the html tag to add the proper attribution as part of the embed.

**Comment by Tanuj22** [comment]
@aldenstpage Can I work on this?

**Comment by nathzi1505** [comment]
Can I contribute to this issue?

**Comment by aldenstpage** [comment]
Hi @nathzi1505 and @Tanuj22, as the README says, you should feel free to work on tasks that are marked with help wanted. You should both check out branches and work in the open on the issue. Consider collaborating together to prevent redundant work.
