### ISSUE TITLE
Link to documentation of the Analytics server is not loading

### ISSUE THREAD

**Issue by krysal** [creativecommons/cccatalog-api#449]
## Describe the bug

The Analytics server documentation doesn't load.

## To Reproduce

1. Go to [link](https://api.creativecommons.engineering/analytics) on the CC Search Analytics' [README](https://github.com/creativecommons/cccatalog-api/tree/master/analytics)
2. It redirects to http://api.creativecommons.engineering:8080/analytics/
3. See error

## Expected behavior

Show the docs.

## Screenshots
![Captura de pantalla de 2020-03-09 17-18-04](https://user-images.githubusercontent.com/9145885/76258616-50162b00-622a-11ea-89d0-d6351040bf9f.png)
_Text in Spanish._

## Desktop (please complete the following information)
 - OS: Debian GNU/Linux 9
 - Browser: tested in both, Chrome (v80) & Firefox (68.5)

**Comment by aldenstpage** [comment]
It seems like there was an environmental issue preventing the ReDoc documentation from loading, which has been fixed.
