### ISSUE TITLE
A small documentation error under image_search

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-api#452]
## Describe the bug
The 400 Bad Request response for the `images/` endpoint has keys: `error_type`, `field` and 
`detail`. But in the documentation, it is mentioned that the keys are: `error`, `fields` and `detail`.

Compare and contrast the api response in https://api.creativecommons.engineering/v1/images?q=+ and the keys for 400 response type under https://api.creativecommons.engineering/v1/#operation/image_search

**Comment by Vineet-Sharma29** [comment]
Can I work on this @aldenstpage @makkoncept ?

**Comment by kgodey** [comment]
@Vineet-Sharma29 our new contribution guidelines say that you no longer need permission to work on issues tagged "help wanted" or "good first issue".

Please read our [Contribution Guidelines here](https://opensource.creativecommons.org/contributing-code/).

**Comment by priscacodes** [comment]
I am working on this issue. @kgodey
