### ISSUE TITLE
Determine ideal compression for Rekognition images

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#471]
Related to #464.

## Description
We need to determine the ideal amount of JPEG compression to use for images that we feed to Rekognition. See this discussion; it looks like compression reduces the quality of Rekognition detection. We should do some experiments to determine the best tradeoff between filesize and detection accuracy. Ideally, we should use as much compression as possible without diminishing label quality, as storing larger files has a serious impact on crawl performance and storage costs.  It looks like our current choice (quality=30/100) is too aggressive.

Use the [Rekognition demo](https://console.aws.amazon.com/rekognition/home?region=us-east-1#/label-detection) to gather samples on a diverse set of Flickr images. Try multiple levels of compression for each image.

## Deliverables
A CSV with the following fields: `image_url`, `quality`, `labels`.
- `image_url` is the URL of the image that is being tested.
- `quality` is the JPEG quality, which should range from 0.3 to 0.9 in intervals of 0.1.
- `labels` is the labels from [AWS Rekognition](https://console.aws.amazon.com/rekognition/home?region=us-east-1#/label-detection) for the image at that compression ratio.

For example:
```
image_url, quality, labels
https://example.org/image.jpg,0.3,{"vehicle": 0.70, "volvo": 0.48}
https://example.org/image.jpg,0.4,{"vehicle": 0.90, "volvo": 0.88}
https://example.org/image.jpg,0.5,{"vehicle": 0.90, "volvo": 0.88}
https://example.org/image.jpg,0.6,{"vehicle": 0.90, "volvo": 0.88}
```
. . .and so on. We'll want to collect this data for **100 images** to start.

Please put your resulting code and data somewhere in the scripts directory (cccatalog-api/cccatalog/scripts).
## Additional context

Please see the corresponding conversation in PR #468 for additional context (copied below for reference).

>Full size:
![image](https://user-images.githubusercontent.com/6829750/77672673-77d6f400-6f89-11ea-9560-810e31ecffc8.png)

>Thumbnailed (modified for quality=80):
>![image](https://user-images.githubusercontent.com/6829750/77673220-2e3ad900-6f8a-11ea-8c8b-cd5375471749.png)

>Thumbnailed (modified for quality=70):
>![image](https://user-images.githubusercontent.com/6829750/77673068-f764c300-6f89-11ea-92d8-0701a5c4d2d4.png)

>Thumbnailed (modified for quality=60):
>![image](https://user-images.githubusercontent.com/6829750/77673536-97225100-6f8a-11ea-90b7-a3166fcedcfc.png)

>Thumbnailed (modified for quality=30):
>![image](https://user-images.githubusercontent.com/6829750/77673436-735f0b00-6f8a-11ea-8087-8b069e2f0d34.png)

>So, for that image at least, the 'labeling' goes away at quality=60

_Originally posted by @mathemancer in https://github.com/creativecommons/cccatalog-api/pull/468_

**Comment by kgodey** [comment]
I mainly want to say that I love that picture of Erdős, @mathemancer.

**Comment by enelesmai** [comment]
What is the expected deliverable here? I would like to work on it,

**Comment by aldenstpage** [comment]
Hi @enelesmai, I added a Deliverables section to the ticket. I think a CSV would be a good way to communicate the results of this experiment.

**Comment by enelesmai** [comment]
Great! so I'll star working on it and let you know if I have another question

**Comment by aldenstpage** [comment]
Hi @enelesmai, any updates on this? No problem if there hasn't been any progress, I'm going to look into this in our next sprint as a prerequisite of setting up our image crawler.

**Comment by Arunhari333** [comment]
Some of the issue seems to be solved. What are the remaining tasks?

**Comment by aldenstpage** [comment]
@Arunhari333, I don't think anyone has had the time to take this on yet so the whole task remains. It's a blocker for scraping images so I'll be taking a look at it this week.

**Comment by aldenstpage** [comment]
It turns out that someone has published some research on this subject already. See [How Image Downscaling and JPEG Compression Affects Image Classification Performance](https://www.diva-portal.org/smash/get/diva2:1351106/FULLTEXT01.pdf). I don't see a point in reproducing these experiments.

If you scroll down to the results section, you will see that object recognition accuracy is only slightly impacted by moderate levels of compression(which is in line with our own informal experimentation with Rekognition). After reviewing the related work and results, my conclusion is that 30 is a good tradeoff between classification accuracy and file size for our use case.
