### ISSUE TITLE
I Indivisuals Checkbox for Images,Videos, Audios

### ISSUE THREAD

**Issue by 1997SHUBHAM** [creativecommons/cccatalog-api#472]
## Problem Description
New frontend page for images,audio and video 

## Solution Description
when you click any of checkbox at a time
i will call that particular api for data

## Alternatives
AFTER IMPROVEMENT IT WILL LOOK LIKE THIS

![IMG_20200329_202534](https://user-images.githubusercontent.com/50594486/77852401-14083180-71fc-11ea-9eb7-00c231366305.jpg)

**Comment by 1997SHUBHAM** [comment]
Main Motive of this is that whenever you select the type of checkbox you will get that type of data using  API which is associated with it.

**Comment by aldenstpage** [comment]
Please post any frontend proposals in the [corresponding repository](https://github.com/creativecommons/cccatalog-frontend)
