### ISSUE TITLE
Create a Django admin interface for handling pending mature reports and DMCA requests

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#473]
A rough description of how this interface will work:

>Table Interface Options

>After content is reviewed, we’d like to continue to store it in the table, so we have a record of all user reports. However, any content already reviewed and therefore marked with “no” should by default not be shown (i.e. be filtered out) from the Django admin interface. A backend user of the interface should be able to select it for inclusion, should they need to review prior actions.

>The following actions should be available for each row in the table:

>Mark Mature

>    The metadata for the record gets updated to indicate the content is mature
>    Note: by default, we will hide mature content in the UI, but we will introduce a filter for users to purposefully show it

>De-Index Content

>    The piece of content is permanently de-indexed in the API
>    Note: this does not delete the record from the Catalog, but it introduces a flag to ensure that it >no longer shows in search results

**Comment by annatuma** [comment]
Updated description to replace "NSFW" with "Mature", per discussion on meta ticket.

**Comment by aldenstpage** [comment]
Here's a demo of how this will work:
![1](https://i.imgur.com/dkN2qgY.png)
Here's a list of reports. This can be populated through users using the report interface or you can manually make one yourself through the admin UI interface. This is nice because it will let you avoid being rate limited like an anonymous user would (end users will likely have a maximum number of reports they can make per day to prevent abuse). 

Clicking on the report status takes you to the report detail page, where you can determine what action needs to be taken against the image.
![2](https://i.imgur.com/jXxFoCS.png)

You have your choice between adding a mature tag, deindexing the work (for copyright / contraband), or taking no action (if a user got too trigger happy). You can also delete the report if you think it looks like it looks particularly spammy.

After you save a change to a report's status, it cannot be changed again.

![3](https://i.imgur.com/VNZ74Bs.png)

**Comment by annatuma** [comment]
This looks super! Thank you so much for the walk through in the ticket and answering my questions on Slack.

As discussed the default filter is not an issue, it's quick enough to click on "pending_review" to deal with any new complaints.
