### ISSUE TITLE
Create an endpoint for accepting reports on images

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#474]
We need an endpoint for accepting reports from users about images that they perceive as being inappropriate for search results. The report will go to a database table called `nsfw_reports`, where we will be able to make a judgement call on what the next steps with the image are (either no action, hiding behind an opt-in NSFW checkbox, or deleting entirely). 

Example request:
```
POST /v1/images/{uuid}/report
{
    identifier = 694d7022-69a6-40d6-9198-6251d48a7eb1,
    reason = 'adult'
}
```

Users can also pick "other" and provide a description of what the problem with the image is.

```
POST /v1/images/{uuid}/report
{
    identifier = 694d7022-69a6-40d6-9198-6251d48a7eb1,
    reason = 'other',
    description = 'reasons why this image upsets me'
}
```

This should then result in the creation of a database entry in `nsfw_reports` with a similar schema.

`reason` can be any one of the following: "adult", "other", or "dmca"

`description` is a free-form string of up to 500 characters (minimum 20) where the reporter can give us more details. It should be required if a user clicks "other", but ignored if a user picks "adult" or "dmca".

---
See https://github.com/creativecommons/cccatalog-frontend/issues/848 for full implementation details.

**Comment by Vineet-Sharma29** [comment]
@aldenstpage can I work on this?
