### ISSUE TITLE
Collect height, width metadata during image scraping

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#475]
Blocking on https://github.com/creativecommons/cccatalog-api/issues/464

After scraping an image, we should publish the dimensions metadata to a Kafka topic for pulling into the `cccatalog`.

Topic: `resolution_updates`
Messages should be JSON with this schema:
```
{
    "height": 1024,
    "width": 768,
    "uuid": "xxxx-xxxxxxx-xxxxxxx"
}
```

**Comment by Vineet-Sharma29** [comment]
@aldenstpage can I work on this?
