### ISSUE TITLE
[Feature] Use metadata keywords to help detect if something is NSFW

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#482]
## Problem Description
We are trying to make NSFW content in CC Search "opt-in". We can catch a lot of NSFW content by using API specific filters and relying on moderation "upstream" at the source, but sometimes things slip through.

## Solution Description
One way we can help prevent this is scanning for NSFW profanity and slurs in the title/tags/artist name and settings `nsfw = True` in the metadata field if it fails the check. There are [3rd party lists of dirty words](https://www.cs.cmu.edu/~biglou/resources/) that can help us achieve this. In my experience moderating content on CC Search, this will help prevent a lot of embarrassment and indignant emails from teachers.

We can do a one-time scan-and-filter relatively easily, but we will also need a way to filter new content as it is ingested.

## Additional Context
[The Scunthorpe Problem](https://en.wikipedia.org/wiki/Scunthorpe_problem)

**Comment by Mr-burme** [comment]
I hope this gets implemented. I got dick picks in one of my school projects.
