### ISSUE TITLE
/healthcheck endpoint should check for Elasticsearch availability

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#487]
During deployments, our load balancer repeatedly polls the `/healthcheck` endpoint to check that the server is reachable. If this check succeeds, the newly deployed instance starts receiving production traffic. Right now, if Elasticsearch is not responsive, `/healthcheck` will still return `200 OK`.

The healthcheck endpoint should check the health of the `image` index in Elasticsearch using the [cluster health API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html). If it is unavailable, return error 500. Log an informative message explaining why the healthcheck failed.

Because the healthcheck endpoint may be called many times, and Elasticsearch calls are not free, we should cache the response of Elasticsearch for up to 10 seconds per call.

**Comment by madewithkode** [comment]
Hi Alden, this looks interesting, I'd love to work on it.

**Comment by madewithkode** [comment]
Hi Alden in order to check the health of the `image` index in the /healthcheck view, I'm trying to use the urllib's `urlopen()` method to make a request to Elasticsearch's  cluster API this way:

`cluster_response = urlopen('http://0.0.0.0:8000/_cluster/health/image')`

However, I keep getting a 404. Is there something I'm doing wrong?

**Comment by madewithkode** [comment]
> Hi Alden in order to check the health of the `image` index in the /healthcheck view, I'm trying to use the urllib's `urlopen()` method to make a request to Elasticsearch's cluster API this way:
> 
> `cluster_response = urlopen('http://0.0.0.0:8000/_cluster/health/image')`
> 
> However, I keep getting a 404. Is there something I'm doing wrong?

Figured this, didn't know elastic search was running on a seperate host/port :)

**Comment by aldenstpage** [comment]
It would be best to use the equivalent `elasticsearch-py` query instead of making direct calls to the REST API. [Here's](https://discuss.elastic.co/t/how-to-get-cluster-health-using-python-api/25431) an example for getting the cluster health; there ought to also be a way to narrow the query to the `image` index.

**Comment by madewithkode** [comment]
Alright...would look at the suggestion.

**Comment by madewithkode** [comment]
Hi Alden, I'm here again :)
I'd love to ask, what status specifically signifies the availability of the `image` index. 
`red`, `yellow` or `green` ? or should i leave out this detail in the query since I'm using an already established connection instance from `search_controller.py` which waits for a `yellow` status by default.

**Comment by madewithkode** [comment]
### Update: 
I've successfully managed to query the health of the entire cluster, using the Elasticsearch connection instance gotten from `search_controller.py`. However when i try to limit the health check to just the `image` index, the request never resolves and continues to run forever with no response. And when i try to specify a timeout for the request, i get an "Illegal argument exception" even though `timeout` is a valid kwarg referenced in the [API docs](https://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=health#elasticsearch.client.ClusterClient.health).

It'd be nice to point out that as at the time of writing, I'm yet to successfully run `./load_sample_data.sh` so i don't know if this could be linked to the above problem.

**Comment by madewithkode** [comment]
Hi Alden, Progress Report :)

Successfully got the `load_sample_data.sh` to run,  and so far every other thing is working fine. 
I've also set up the 10s response caching on the `/healthcheck` view using redis and also the error logging.

However, I figured out the reason for the unresponsiveness when querying the elastic search `image` index was that it was non-existent and that the whole cluster index was empty too.

Do I need to do a manual population or something?

**Comment by aldenstpage** [comment]
Hi again Onyenanu – if the index doesn't exist, the healthcheck should fail. This could happen in situation where we are switching Elasticsearch clusters in production and forgot to index data into the new one (or something went wrong while we were loading data). Instead of querying specifically for the `image` index, you could perhaps query for healthchecks of every index in the cluster, and fail the healthcheck if `image` is not among them?

It sounds like it's coming along nicely!

**Comment by madewithkode** [comment]
> Hi again Onyenanu – if the index doesn't exist, the healthcheck should fail. This could happen in situations where we are switching Elasticsearch clusters in production and forgot to index data into the new one (or something went wrong while we were loading data into the new cluster).
> 
> In my experience, the ES Python libs can behave in unexpected ways that you sometimes have to work around. Since it seems like querying specifically for the `image` index health hangs when the index doesn't exist, perhaps you could query for healthchecks of every index in the cluster, and fail the healthcheck if `image` is not among them and green?
> 
> It sounds like it's coming along nicely!

Hey Alden...Many thanks again for coming through with better insights. Suggestion sounds nice, would proceed with it.

And yes, the whole stuff  is getting more interesting, learnt a handful in the few days :)
