### ISSUE TITLE
Documentation should have multiple request samples

### ISSUE THREAD

**Issue by dhirensr** [creativecommons/cccatalog-api#491]
## Problem Description
Hello everyone,
In the documentation https://api.creativecommons.engineering/v1/#operation/register_api_oauth2 I see that curl instructions are given in the docstring (https://github.com/creativecommons/cccatalog-api/blob/a18f75fccdd7345beff820dff4ee69604cd53748/cccatalog-api/cccatalog/api/views/site_views.py#L91-L137) and hence user can just view it as a text box, and needs to manually copy that for using it. 
I think it's wrongly being used because it should be used somewhat like as shown in the image
![api](https://user-images.githubusercontent.com/16983076/81627122-c5a2a100-93fd-11ea-99e7-25c856f97883.png)

## Solution Description
To use this we should use redoc [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md) (x-code-samples in our case)

**Comment by dhirensr** [comment]
@aldenstpage : I would like to work on this and will send a PR in a week .

**Comment by dhirensr** [comment]
@kgodey @aldenstpage 
* Few ideas regarding docs
** All response parameters doesn't have a description. I would like to add that just to make it more explicit and clear.
for eg : in recommendations identifier description is missing.(https://api.creativecommons.engineering/v1/#tag/recommendations)
** I would like to extend by adding a description for each title of the page. Like for images something like " "CC Catalog API searches across more than 300 million images from open APIs and the Common Crawl dataset. Currently CC Catalog API only searches images, with the ultimate goal of providing access to all 1.4 billion CC licensed and public domain works on the web. "
Do you think it would be helpful for API docs?
** Also I noticed there are 2 routes for same thing. namely http://api.creativecommons.engineering/statistics/image and https://api.creativecommons.engineering/v1/sources . Is it by choice or a bug?
** The format parameter is not mentioned for any of the routes but its actually shipped with django rest framework. I think it would be good for developers to know about this option.
for eg: https://api.creativecommons.engineering/v1/oembed and https://api.creativecommons.engineering/v1/oembed?format=api and https://api.creativecommons.engineering/v1/oembed?format=xml and https://api.creativecommons.engineering/v1/oembed?format=json

I would like to confirm which of the points would be helpful for the docs and then I could start working on them.

**Comment by gabbyprecious** [comment]
Is this still open? I would love to propose a solution

**Comment by dhirensr** [comment]
@gabbyprecious : if there are minor changes like mentioned above I think you can use this ticket, otherwise you could create a new ticket.
