### ISSUE TITLE
Missing documentation for OEMBED

### ISSUE THREAD

**Issue by dhirensr** [creativecommons/cccatalog-api#494]
## Describe the bug
The documentation for OEMBED module is not properly designed because https://api.creativecommons.engineering/v1/oembed it does not mention about the params needed, so one always get's a 404
Then I saw in the implementation here https://github.com/creativecommons/cccatalog-api/blob/a18f75fccdd7345beff820dff4ee69604cd53748/cccatalog-api/cccatalog/api/views/image_views.py#L271 
the url param was missing hence I was getting 404 , I think this should be mentioned in the docs

## To Reproduce
https://api.creativecommons.engineering/v1/oembed always 404
https://api.creativecommons.engineering/v1/oembed?url="someurl" returns some other status

**Comment by aldenstpage** [comment]
Thanks for reporting this. Could you please consolidate documentation defects under one issue (like this one: https://github.com/creativecommons/cccatalog-api/issues/491)?

**Comment by dhirensr** [comment]
@aldenstpage : thanks for the reply. I would consolidate them and send a PR this weekend :smile:
