### ISSUE TITLE
Help wanted! Can someone please provide an exaple of this api?

### ISSUE THREAD

**Issue by Mr-burme** [creativecommons/cccatalog-api#501]
Hi, I would like to use this API in my python application, but I don't know how.

I want the code to get one CC0 1.0 license image by searching one word. I don't know if this API allows downloading the image directly if not the image URL is fine.

Can someone please share some python code that can get an image URL or download the image?

If this is not possible that's okay I'll try to find another way.

As you can tell I m new to programming and I am sorry if my question doesn't make sense or it is tedious to deal with my question.

Thank you very much,
Ernests

**Comment by Tanuj22** [comment]
Hey @Mr-burme, there can be multiple images with `CC0 1.0` license and searching one word. For Eg. https://api.creativecommons.engineering/v1/images?q=hello&license=cc0&license_version=1.0 contains multiple images with `CC0 1.0` license and word say `hello`. Do you want a specific image?

**Comment by Mr-burme** [comment]
Hi, I want to get the first image that shows up in the results.
Thanks!
Ernests

**Comment by Tanuj22** [comment]
This will give you the url of the first image in the results.
```
import requests

r = requests.get("https://api.creativecommons.engineering/v1/images?q=hello&license=cc0&license_version=1.0")
data = r.json()
url = data['results'][0]['url']
print(url)
```

**Comment by Mr-burme** [comment]
Thank you so much. You have made my day.
Thanks again.
Ernests
