### ISSUE TITLE
Enable CDN for thumbnails

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#514]
For users who are not based in the United states or within a couple thousand miles of it, thumbnails will load slowly because they need to come from our server half a world away. We should make sure that thumbnails are cached through Cloudflare.

**Comment by aldenstpage** [comment]
We had Cloudflare's CDN enabled for the cc.engineering domain but not for its subdomains. This has been fixed.

It may take a while before common queries are cached.

**Comment by makkoncept** [comment]
Hi @aldenstpage. The `thumbs` endpoint is showing `internal server error`. Is it because that maybe queries are not cached yet?

![Screenshot from 2020-06-16 18-40-20](https://user-images.githubusercontent.com/34679965/84778601-d8ae1f80-b000-11ea-83f3-b4e9a828a316.png)

**Comment by aldenstpage** [comment]
Could you include some search terms and links? When I do a search, all of the thumbnails load.

**Comment by makkoncept** [comment]
https://api.creativecommons.engineering/v1/images?q=cat Every thumbnail I tried on this search result gives the error.

GIF for reference (opening `url` and `thumbnail` pairs)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34679965/84793357-9db4e780-b012-11ea-87f7-b21994806efd.gif)

**Comment by aldenstpage** [comment]
Thanks for raising that! I hadn't noticed a configuration issue because the frontend falls back to full resolution images if the thumbnails don't load properly. It's fixed now.
