### ISSUE TITLE
`null` license URLs in prod.

### ISSUE THREAD

**Issue by mathemancer** [creativecommons/cccatalog-api#525]
## Describe the bug

The API returns `null` for license URL when license URL is `null` in the `meta_data` field of the `image` DB, even in the case where a valid license / license version combo is available.

See https://api.creativecommons.engineering/v1/images/9b900d3b-27d9-411f-8366-a0152eefb34a for an example.

## To Reproduce

1. Go to https://ccsearch.creativecommons.org/photos/724c8237-69f8-4af3-8dff-ab21202a592d
2. Click on the license links
3. Note that the links are invalid.

## Expected behavior

In the case where `license_url` is null in the `meta_data` field of the `image` DB, we should construct the URL as before.

**Comment by aldenstpage** [comment]
This is no longer reproducible in production.
