### ISSUE TITLE
Switch `source` with `provider`

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#531]
For the sake of consistency, we would like to refer to source platforms as `sources`, and then break further break each collection down by `provider`. For example, the NASA account on Flickr could be labeled `provider=flickr` and `source=nasa`.

**Comment by kgodey** [comment]
@aldenstpage I think we decided it would be `provider=flickr` and `source=nasa` cc @mathemancer

**Comment by aldenstpage** [comment]
Fixed!

**Comment by mathemancer** [comment]
This is correct by my recollection, and is what the current new schema will reflect in the upstream DB.  The newly-implemented schema (restricted to provider/source-related columns) is described below:

Relative to the old `image` table, the changed interpretations of three fields in the `new_image` table are:
- `provider`: This is the 3rd party provider that provides the image metadata we've collected.  Think of this as the 'domain' of the image.  Copied from old `provider` column.
- `source`:  This is a collection of images from some source, possibly hosted as a subset of a provider's images, possibly as subsets of multiple provider's images.  This used to be `provider`, and the initial data is copied from that column.
- `ingestion_type`: This is a flag letting us know (for now) whether the metadata was ingested from Common Crawl or a Provider API Script.  This used to be `source` in the case of metadata ingested from Common Crawl, and was the same as `provider` in the `image` table for all other metadata.

**Comment by mathemancer** [comment]
The values of `ingestion_type`, by the way, will be `provider_api` or `commoncrawl`
