### ISSUE TITLE
Phase out view_count column

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#540]
We don't need the view_count column because the analytics API makes it obsolete. It should be removed from the schema through migrations, and the django cron job that updates it (as well as the accompanying over-engineered redis caching code) should be deleted.

**Comment by ritesh-pandey** [comment]
I am taking this up.

**Comment by ritesh-pandey** [comment]
Is the cron job that we are talking here is `SaveCachedTrafficStats`?

**Comment by ritesh-pandey** [comment]
Module `api.utils.view_count` now contains a single method `_get_user_ip`.

Should we rename the module to a more relevant name like `api.utils.request`?

**Comment by aldenstpage** [comment]
>Is SaveCachedTrafficStats the cron job that we are talking here?

That's right.

>Should we rename the module to a more relevant name like api.utils.request?

Yep, that's fine

**Comment by ritesh-pandey** [comment]
Do we generate migrations on dev machine and push them to repo or do we follow any other mechanism?

**Comment by aldenstpage** [comment]
Yeah that's the correct process to follow. After the PR has been merged I will run the migration manually during deployment.

**Comment by ritesh-pandey** [comment]
PR created.
