### ISSUE TITLE
[Feature] Metadata to classify providers

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-api#571]
## Problem

While we don't want the current frontend design of cc search to lead our api design, we currently _hardcode_ classifications of the providers in cc search, and would like to consider adding a mechanism to do this via the api. The only current categories are 'museum' and 'other', but this may be extended in the future, especially as our number of sources grows.

## Description

Implement a category system for sources in the database. Could be a single category or multiple depending on the final requirements.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by aldenstpage** [comment]
Who classifies new content sources when they are added to our database, and how? Do we want this to be configurable through the content provider interface? @annatuma @kgodey

**Comment by kgodey** [comment]
we don't have an answer yet, this will depend on the design work that @annatuma and @panchovm are doing on sources/collections and may take a while. we'll update the issue once there are more details.
