### ISSUE TITLE
Invalidate filter cache after updates to content provider table

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#583]
## Problem
After changing the status of `filter_content` in the content provider admin interface, it can take up to 20 minutes before the status of the filter changes.
## Description
The filter cache (see search_controller.py) should be invalidated every time there is an update to content_provider. We should also make sure that the contents of the /v1/sources endpoint itself isn't caching anything besides the number of images for each source.

**Comment by rochisha0** [comment]
Can I take this issue @aldenstpage ?

**Comment by aldenstpage** [comment]
Yes, that would be great @rochisha0!

**Comment by aldenstpage** [comment]
(the cache interval has been reduced significantly from 20 minutes, but it would still be good to immediately invalidate the cache when this is updated)

**Comment by rohitgeddam** [comment]
@rochisha0 are you working on this one? If Not i would like to work on It.

**Comment by adrijshikhar** [comment]
Is this issue still available to work on?

**Comment by kgodey** [comment]
go ahead @adrijshikhar

**Comment by adrijshikhar** [comment]
From what I can understand is whenever there is an update in `ContentProvider` db, the filter cache should be reset. Please correct me if I am wrong.

**Comment by rajdesai24** [comment]
I'd really like to get started with this issue, can I help in anyway

**Comment by rajdesai24** [comment]
@dhruvkb

**Comment by kgodey** [comment]
@rajdesai24 we don't currently have a staff maintainer for this project, we cannot merge issues to this repo for now. please give us a couple of weeks.

**Comment by rajdesai24** [comment]
Not an issue @kgodey please do let me know if I can help in anyway with the python backend. Thanks :0

**Comment by kshitij86** [comment]
@kgodey Has this issue been resolved?

**Comment by kshitij86** [comment]
@kgodey How should the invalidation of the filter cache be performed?

**Comment by dhruvkb** [comment]
Hey @kshitij86, we might not be accepting PRs to this this repo for the time being. I would encourage you to contribute to other projects ([Project List](https://opensource.creativecommons.org/contributing-code/projects/)) or issues ([Issue Finder](https://opensource.creativecommons.org/contributing-code/issue-finder/)).

**Comment by kgodey** [comment]
@kshitij86 Please see this blog post for more information: https://opensource.creativecommons.org/blog/entries/2020-12-07-upcoming-changes-to-community/
