### ISSUE TITLE
Send crawled images to be processed by AWS Rekognition

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#584]
We have a feed of image metadata coming in from our crawler. We want to feed the 77MM images we've deemed worth crawling to Rekognition.

Use a Kafka topic to direct EC2 worker instance(s) to feed images to Rekognition. We should store the full response from Rekognition, including any bounding boxes, in a topic named `rekognition_results`.

**We can't start feeding images to Rekognition until we have opted out of [Amazon's AI services](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_ai-opt-out.html)**.

- [x] Opted out of AI services

**Comment by aldenstpage** [comment]
I've opted us out of AI services for all regions using the [organization policy console](https://console.aws.amazon.com/organizations/home).

**Comment by aldenstpage** [comment]
I've opted us out of AI services for all regions using the organization policy console.

**Comment by aldenstpage** [comment]
We're having conversations with AWS about architecture and cost minimization, so I'm marking this as blocked for the time being.

**Comment by aldenstpage** [comment]
This is blocked while we wait for a deal with AWS to be finalized
