### ISSUE TITLE
/v1/thumbs should time out eventually

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#602]
## Description
If we are having a hard time loading a 3rd party image through our proxy, we should give up thumbnailing it. The frontend will fall back to the full sized image.

If we can't answer thumbnail requests quickly enough, our servers' workers become swamped with thumbnailing requests.

**Comment by dravadhis** [comment]
I want to work on this issue. How should I go about this?

**Comment by tushar912** [comment]
@aldenstpage  I would like to work on this. Can u explain this issue a bit.

**Comment by aldenstpage** [comment]
Hi @tushar912, I'd be happy to answer any specific questions you have about the ticket

**Comment by manav1403** [comment]
@aldenstpage Is it correct that for this issue we have to set a timeout on request when full size is false and if the request exceeds timeout then send the response of the full-sized image
