### ISSUE TITLE
Source parameter returns InputError

### ISSUE THREAD

**Issue by aod-123** [creativecommons/cccatalog-api#613]
## Description
The docs here https://api.creativecommons.engineering/v1/#operation/image_search list 'source' as a parameter name which was working a couple weeks ago. It seems this parameter was recently renamed to 'sources' but the docs aren't updated. I'm not sure whether this is a purposeful change or a bug?

## Reproduction
1. Try to hit URL using 'source' parameter listed in docs:
http://api.creativecommons.engineering/v1/images?q=cat&license_type=all-cc&page=1&page_size=50&source=woc_tech,wikimedia,thorvaldsensmuseum,svgsilh,statensmuseum,spacex,smithsonian_postal_museum,smithsonian_portrait_gallery,smithsonian_national_museum_of_natural_history,smithsonian_libraries,smithsonian_hirshhorn_museum,smithsonian_gardens,smithsonian_freer_gallery_of_art,smithsonian_cooper_hewitt_museum,smithsonian_anacostia_museum,smithsonian_american_indian_museum,smithsonian_american_history_museum,smithsonian_american_art_museum,smithsonian_air_and_space_museum,smithsonian_african_art_museum,smithsonian_african_american_history_museum,sciencemuseum,rijksmuseum,rawpixel,phylopic,nypl,nasa,museumvictoria,museumsvictoria,met,mccordmuseum,iha,geographorguk,floraon,flickr,europeana,eol,digitaltmuseum,clevelandmuseum,brooklynmuseum,bio_diversity,behance,animaldiversity,WoRMS,CAPL,500px&extension=jpg,jpeg,png
2. When looking in browser this returns a 400 error regarding invalid input for the 'source' field.
3. Next, try opening URL which uses 'sources' as the parameter and the results seem to be returned fine:
http://api.creativecommons.engineering/v1/images?q=cat&license_type=all-cc&page=1&page_size=50&sources=woc_tech,wikimedia,thorvaldsensmuseum,svgsilh,statensmuseum,spacex,smithsonian_postal_museum,smithsonian_portrait_gallery,smithsonian_national_museum_of_natural_history,smithsonian_libraries,smithsonian_hirshhorn_museum,smithsonian_gardens,smithsonian_freer_gallery_of_art,smithsonian_cooper_hewitt_museum,smithsonian_anacostia_museum,smithsonian_american_indian_museum,smithsonian_american_history_museum,smithsonian_american_art_museum,smithsonian_air_and_space_museum,smithsonian_african_art_museum,smithsonian_african_american_history_museum,sciencemuseum,rijksmuseum,rawpixel,phylopic,nypl,nasa,museumvictoria,museumsvictoria,met,mccordmuseum,iha,geographorguk,floraon,flickr,europeana,eol,digitaltmuseum,clevelandmuseum,brooklynmuseum,bio_diversity,behance,animaldiversity,WoRMS,CAPL,500px&extension=jpg,jpeg,png

## Expectation
No errors & clarification on which is the correct parameter name and updated documentation if necessary.

## Environment

 - Device: Desktop PC
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.83

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by aldenstpage** [comment]
I did some git spelunking, I don't think we ever accepted `sources` as a parameter (maybe you can dig up a commit that proves me wrong). The reason your second query works is because `sources` isn't a valid parameter and thus does not actually narrow down the search any further / get validated like `source` would.

Most likely, one of the sources that you hardcode in your list has been removed or has a typo. Unfortunately the current error message for this parameter makes it difficult to figure out which one; v1.8.1 will fix this (see https://github.com/creativecommons/cccatalog-api/pull/614). I'll check in here once that's in production.

**Comment by aldenstpage** [comment]
Ok, now we have some better error messages in place, and the root issue is apparent:

```
HTTP 400 Bad Request
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "error": "InputError",
    "detail": "Invalid input given for fields. 'source' -> Source 'museumvictoria' does not exist.",
    "fields": [
        "source"
    ]
}
```

It looks like you have both museumvictoria and museum*s*victoria in your query. Only the latter is valid.

**Comment by aod-123** [comment]
@aldenstpage Thanks for the info, was 'museumvictoria' recently removed? That source was included at the time we were testing a week or so ago and all was working well. I'm a bit concerned that changes to the source list would break any older queries that might have listed those sources? 

I'm fine with updating our code to match this change but I feel it would be nice if the API could disregard any invalid sources that might be listed or were listed previously. That way if only one source is invalid like in this case it could still return results for all the others. Mostly I'd just like to avoid having to deploy hotfixes to patch the query whenever the source list changes, should I log this as a feature request?

**Comment by aldenstpage** [comment]
`museumvictoria` was never a real source; the correct code is `museumsvictoria`. It looks like it was included in the list of valid sources as a fat finger typo, which someone fixed.

I agree that there isn't really a need to be so strict with source validation, especially since the list of sources can change arbitrarily. We'll remove that requirement in the near term. https://github.com/creativecommons/cccatalog-api/issues/615

**Comment by aod-123** [comment]
@aldenstpage Ah, yeah I was curious about that one but didn't really question it. Thanks for the quick responses and quick resolution, I look forward to seeing #615 soon!
