### ISSUE TITLE
Invalid sources should be ignored instead of a fatal 400 error

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#615]
## Problem
(Discussed in https://github.com/creativecommons/cccatalog-api/issues/613)
When the list of sources changes, queries with former sources are rejected as invalid.

## Description
Rather than completely reject the query, we should silently exclude non-existent sources. This behavior should be clearly documented in the OpenAPI schema.

**Comment by dynamoh** [comment]
Hey, @aldenstpage I want to work on this issue, can you assign me this issue.

**Comment by kgodey** [comment]
go ahead @dynamoh

**Comment by tushar912** [comment]
can i work on this.

**Comment by kgodey** [comment]
sure go ahead @tushar912

**Comment by krysal** [comment]
Hi 👋🏻 This seems to be fixed in #621, missing something to do?

**Comment by kgodey** [comment]
I think it just wasn't closed automatically, closing.
