### ISSUE TITLE
Deduplicate attribution events in analytics database

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-api#629]
We found an issue in the frontend, where we are triple counting attribution events:
https://github.com/creativecommons/cccatalog-frontend/issues/1231

Once this is fixed, we'll need to go through historical data to deduplicate attribution events, to ensure they're correct historically as well.

**Comment by zackkrida** [comment]
Noting that the tripled events from the front-end are concurrent, so should all have very similar or even identical timestamps in our db, which could be an easy way to handle deduping.
