### ISSUE TITLE
Research for Audio APIs

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-api#635]
[placeholder; ticket work required]

**Comment by rajdesai24** [comment]
@dhruvkb  can I take this?

**Comment by rajdesai24** [comment]
@zackkrida can I help in some way?

**Comment by rajdesai24** [comment]
@dhruvkb can I take this up?

**Comment by zackkrida** [comment]
@rajdesai24 We're not ready to move forward with this yet—we will update you hear though if anything changes. Thanks for inquiring!

**Comment by rajdesai24** [comment]
no problem please let me know where to contribute @zackkrida , I wanted to help in some way with the python back end , would appreciate your guidance
